### ISSUE TITLE
Move up / Move down buttons

### ISSUE THREAD

**Issue by crlcu** [crlcu/multiselect#10]
In issue #9 @liuyug asked to have this feature - this is a separate issue to better keep tracking of what was done.

**Comment by gtrdblt** [comment]
Hi,

I'd like to know if there is any progress on this feature request ? 

Thank you.

Sincerly,

G.

**Comment by crlcu** [comment]
Hi @gtrdblt 
Nope, not yet - sorry.

**Comment by gtrdblt** [comment]
Ok thanks :) I'll have a look anyway !

Thank you for your work :)

**Comment by crlcu** [comment]
At this moment I'm not sure how to implement this - as there might be a lot of situations :).
E.g.: 
- you chose to move things up / down on the left side
- then move some options to the right side
- rearrange them on right side with up / down buttons
- then chose to move some of them back to the left side

What would you expect to see on the left side ?

**Comment by crlcu** [comment]
Do you think it might be useful to keep something like ... `left side order` and `right side order` ?

**Comment by gtrdblt** [comment]
I do get your point. 

For my specific use case, the point is to have the left side always sorted by alphabetical order, and to have buttons to be able to change the position of an item in the right side list. 

The point is to finally get the right side list with the items ordered as displayed. 

For example, the left side could be [i1, i2, i3, i4, i5] and the right side : [i3, i1, i4]; and it is mandatory for me that the order stays that way, and that I could insert i2 between i3 and i1 (and for that, buttons to move an item up or down is quite nice :smile: )

My point is to get the exact same look&feel as the struts optiontransferselect system.

**Comment by crlcu** [comment]
Ok,
So basically you would like to be able to move `options` up / down just on the right side.
I'll think about that and try to implement something in the next week.

**Comment by gtrdblt** [comment]
Yes indeed ;)

That would be nice ! But don't rush for it !

Thanks
Le ven. 26 août 2016 à 13:00, Adrian Crisan <notifications@github.com> a
écrit :

**Comment by crlcu** [comment]
Hi @gtrdblt 

I've mocked something to handle the move up/down.
You can checkout the latest [release](https://github.com/crlcu/multiselect/releases/tag/v2.3.0)

Any feedback will be much appreciated.

**Comment by gtrdblt** [comment]
Thank you really much ! I'll try it on monday as I'll be away from my computer this week-end !

**Comment by gtrdblt** [comment]
Hi,

It does work perfectly as intended :) Thank you really much :)
