### ISSUE TITLE
Disabling search input suggest browser cache

### ISSUE THREAD

**Issue by gfStudioTesta** [crlcu/multiselect#101]
Is there a way to disable search input auto suggest form browser cache ?

**Comment by crlcu** [comment]
Think adding autocomplete="off" might do the trick.

**Comment by gfStudioTesta** [comment]
newest browser ignore it

**Comment by gfStudioTesta** [comment]
maybe assign a random name instead of q could be the solution

**Comment by gfStudioTesta** [comment]
name="'+(Math.random()*1e32).toString(36)+'"

**Comment by crlcu** [comment]
Keeping in mind that the search input is provided by the developer that uses this plugin, this is already possible.
See http://crlcu.github.io/multiselect/examples/search.html
