### ISSUE TITLE
not working on mobile?

### ISSUE THREAD

**Issue by wim-mertens** [crlcu/multiselect#103]
On mobile (iphone6) it doesn't seem to work, the select options aren't being rendered (0 items)

**Comment by HemanthGali** [comment]
Even i'm facing problem in mobile(iphone6). please help me fix the issue.

**Comment by crlcu** [comment]
Seems like this is an issue on ios devices.
I'm still trying to find a fix for this issue.
I'll get back to you once I have some news.

**Comment by crlcu** [comment]
Seems like the `select[multiple]` is not supported by some browsers on mobile devices.
