### ISSUE TITLE
Please update NPM package to current version.

### ISSUE THREAD

**Issue by Herbis** [crlcu/multiselect#105]
Hi,
Could you please update your plugin on NPM to the current version? 
https://www.npmjs.com/package/multiselect-two-sides

Thanks!

P.S. Thanks for such a useful plugin.

**Comment by crlcu** [comment]
Hi,
Thanks for raising this issue.
It's done now.

**Comment by crlcu** [comment]
Somehow I have mixed up the versions on npm as I tried to publish v2.3.7 and v2.3.6 after I have published v2.3.8
I'll get back to you once I'll manage to publish again v2.3.8
