### ISSUE TITLE
afterMoveUp / afterMoveDown

### ISSUE THREAD

**Issue by jimmy84** [crlcu/multiselect#107]
Hi,

Is it possible to have callback for afterMoveUp / afterMoveDown event?

$('#multiselect').multiselect({
afterMoveUp: function (right, options) { ... }
afterMoveDown : function (right, options) { ... }
});

**Comment by crlcu** [comment]
Hi @jimmy84 
This feature is now done - see v2.3.9

**Comment by jimmy84** [comment]
I believe there is typo on MoveDown function

self.callbacks.**afterMoveUp**( $options );

**Comment by jimmy84** [comment]
I'm not sure is this intended, but the $options passed in is different.

Aren't the $option for event should be from 

self.$right.children(':not(span):not(.hidden)')

instead of 

self.$right.find(':selected:not(span):not(.hidden)');
