### ISSUE TITLE
Is it possible to use two sources and one destination?

### ISSUE THREAD

**Issue by emarket-design** [crlcu/multiselect#108]
We have a need to have two sources and one target (mapping side) selection in a value mapping app. Is it possible to do this?

**Comment by crlcu** [comment]
What about using the http://crlcu.github.io/multiselect/examples/multiple-destinations.html and switch the `select` elements on the UI side ?

**Comment by crlcu** [comment]
Smth like this ?
![image](https://cloud.githubusercontent.com/assets/1661844/25611402/b7417f22-2f2f-11e7-81d2-cd4bfcbcaf24.png)
