### ISSUE TITLE
keep render order with right side

### ISSUE THREAD

**Issue by liuyug** [crlcu/multiselect#11]
right side don't have ``position`` value, so add it.

```
				if ( typeof self.callbacks.startUp == 'function' ) {
					self.callbacks.startUp( self.left, self.right );

                    self.right.find('option').each(function(index, option) {
						$(option).data('position', index);
					});

				}

```

**Comment by crlcu** [comment]
hi @liuyug 

I think it is better to have this in this code block:

```javascript
if (self.options.keepRenderingSort) {
	self.skipInitSort = true;

	self.callbacks.sort = function(a, b) {
		return $(a).data('position') > $(b).data('position') ? 1 : -1;
	};

	self.left.find('option').each(function(index, option) {
		$(option).data('position', index);
	});

	self.right.find('option').each(function(index, option) {
		$(option).data('position', index);
	});
}
```

Anyway this is not going to work very well when there are options in both ``right`` and ``left`` side because in this case a situation when 2 options will have the same position could occur.

**Comment by liuyug** [comment]
Yes, it is better.
I have another problem. You don't identify ``optgroup`` tag. 
May you add ``optgroup`` tag?

**Comment by crlcu** [comment]
Hi @liuyug 
Keeping render sort bug is fixed.
For ``optgroup`` I'll open a new issue and as soon as I can I'll try to implement that feature.
