### ISSUE TITLE
How do I submit the options from both panels through an HTML form?

### ISSUE THREAD

**Issue by dyuk1987** [crlcu/multiselect#110]
I have embedded the plugin in an HTML form, and when I tried to submit the form, no data was submitted, unless I highlighted some of the options on both/either list. So is it possible to submit all the options on both lists without having to highlight (select) them?

I am not sure if the options "submitAllLeft" and "submitAllRight" are meant for that purpose, but I cannot figure out how to work with them.

**Comment by crlcu** [comment]
If you have a look at https://github.com/crlcu/multiselect/blob/master/dist/js/multiselect.js
there's a piece of code that handles this:
```javascript
// Select all the options from left and right side when submiting the parent form
                self.$right.closest('form').on('submit', function(e) {
                    // Clear search inputs
                    self.options.search.$left.val('').trigger('keyup');
                    self.options.search.$right.val('').trigger('keyup');

                    self.$left.find('option').prop('selected', self.options.submitAllLeft);
                    self.$right.find('option').prop('selected', self.options.submitAllRight);
                });
```

Probably you should check if that piece of code is executed for your `form`.

**Comment by dyuk1987** [comment]
Thanks for the quick response.
I am getting the following error when looking into the piece of codes you mentioned.
> Cannot read property '$left' of undefined

**Comment by dyuk1987** [comment]
So I assume it is due to the fact that I didn't use the search feature?

**Comment by crlcu** [comment]
I mean ... you should put a `console.log` in `multiselect.js` - just to check if that piece of code from `multiselect.js` is executed.

**Comment by dyuk1987** [comment]
I knew what you meant. I was just trying to tell you that I have checked the code with some debugging tool, and I found out that the code crashed at these two lines:
> self.options.search.$left.val('').trigger('keyup');
> self.options.search.$right.val('').trigger('keyup');
because I didn't include the search feature of the plugin.

**Comment by crlcu** [comment]
Oh ... damn
That's an issue. Let me fix it.

**Comment by crlcu** [comment]
Should be fixed now. See v2.3.11
