### ISSUE TITLE
Two side jquery multiselect performance issue with large data 

### ISSUE THREAD

**Issue by ashachauhan60** [crlcu/multiselect#111]
Browser hangs  when search data in multiselect having approx 20000 options data.

**Comment by crlcu** [comment]
Yep, I know the current implementation of `search` is so time consuming when there's a large data set.
I'm still thinking of a better way to handle this - but I didn't managed to find one yet.

Any suggestions are welcome.

**Comment by ashachauhan60** [comment]
Modify this code in multiSelect.js

//Bug fix: To Make search case-insensitive : Asha
				//Optimize search
				jQuery.expr[':'].Contains = function(element, i , m){
				   return (element.text || "").toUpperCase().search(m[3].toUpperCase())>=0;
				};

                // append left filter
                if (self.options.search && self.options.search.left) {
                    self.options.search.left.on('keyup', function(e) {
                    	
                    	//Bug fix: Optimized Search : Asha
                    	$(self.left).find("option:not(:Contains(" + this.value + "))").addClass("hidden");
						$(self.left).find("option:Contains(" + this.value + ")").removeClass("hidden");
					    
                        /*var regex = new RegExp(this.value, "ig");

                        self.left.find('option').each(function(i, option) {
                            if (option.text.search(regex) >= 0) {
                                // Remove <span> to make it compatible with IE
                                if($(option).parent().is('span')) {
                                    $(option).parent().replaceWith(option);
                                }

                                $(option).show();
                            } else {
                                // Wrap with <span> to make it compatible with IE
                                if(!$(option).parent().is('span')) {
                                    $(option).wrap('<span>').hide();
                                }
                            }
                        });*/
                    });
                }

                // append right filter
                if (self.options.search && self.options.search.right) {
                    self.options.search.right.on('keyup', function(e) {
                    	
                    	//Bug fix: Optimized Search : Asha
                    	$(self.right).find("option:not(:Contains(" + this.value + "))").addClass("hidden");
					    $(self.right).find("option:Contains(" + this.value + ")").removeClass("hidden");
					    
                        /*var regex = new RegExp(this.value, "ig");

                        self.right.find('option').each(function(i, option) {
                            if (option.text.search(regex) >= 0) {
                                // Remove <span> to make it compatible with IE
                                if($(option).parent().is('span')) {
                                    $(option).parent().replaceWith(option);
                                }

                                $(option).show();
                            } else {
                                // Wrap with <span> to make it compatible with IE
                                if(!$(option).parent().is('span')) {
                                    $(option).wrap('<span>').hide();
                                }
                            }
                        });*/
                    });
                }

And For Select All

actions.rightAll.on('click', function(e) {
                    e.preventDefault();

                    var options = self.left.find('> option:not(.hidden)');
                    if ( options ) {
                        self.moveToRight(options, e);
                    }

                    $(this).blur();
                });
                
                actions.leftAll.on('click', function(e) {
                    e.preventDefault();
                    
                    var options = self.right.find('> option:not(.hidden)');
                    if ( options ) {
                        self.moveToLeft(options, e);
                    }

                    $(this).blur();
                });
