### ISSUE TITLE
Using multiselect as AMD module doesn't work when jQuery globals aren't defined

### ISSUE THREAD

**Issue by danowar2k** [crlcu/multiselect#112]
Hi,

I'm currently using your plugin in a Moodle installation. We're upgrading from Moodle 2.8 to 3.2. Your plugin worked before, when Moodle was primarily using the YUI framework. But Moodle has since started to migrate to using jQuery. It now encourages jQuery+RequireJS+AMD modules.

Your plugin can be used as an AMD module, but there is a case when it doesn't work:
Moodle seems to be configured so that the global variables $ and jQuery do not exist at the time execution of your script starts.

You check if jQuery is defined and stop execution if it isn't. So the script cannot be used this way.

I moved the jQuery existence and version check to a function and only checked for jQuery if no AMD module is defined. It then worked for me. I don't know if that would be the correct way to do it, but I thought you didn't need to check for jQuery if you use the define syntax.

**Comment by crlcu** [comment]
This is fixed now.

**Comment by danowar2k** [comment]
Is it fixed? I'm looking at multiselect.js on master branch. I can't see where you fixed the jquery check in the file...?

**Comment by crlcu** [comment]
Hi @danowar2k,
Could you please do the required changes and create a pull request, as I have quite a lot of work to do and I don't have time to fix this right now.

Thanks in advance.

**Comment by danowar2k** [comment]
I'll have something that will fix this in my big contribution.
