### ISSUE TITLE
How are search filters supposed to work?

### ISSUE THREAD

**Issue by danowar2k** [crlcu/multiselect#118]
Hi,

I'm unsure how search filters are supposed to work in context of multiple destinations.

Is it intended that you only have ONE search filter for all destinations? So that filtering affects all right elements?

Or should each right destination have its own search filter, so you can filter independently?

**Comment by crlcu** [comment]
Each `select` element should have it's own `search input`.

**Comment by danowar2k** [comment]
And each `search input` should filter its own `select` element? Cause I don't think it does this right now, or does it? It seems if you enter a text string, every "right" select is filtered.

```
                    self.options.search.$right.on('keyup', function(e) {
                        if (self.callbacks.fireSearch(this.value)) {
                            var $toShow = self.$right.find('option:search("' + this.value + '")').mShow();
                            var $toHide = self.$right.find('option:not(:search("' + this.value + '"))').mHide();
                            var $grpHide= self.$right.find('option.hidden').parent('optgroup').not($(":visible").parent()).mHide();
                            var $grpShow= self.$right.find('option:not(.hidden)').parent('optgroup').mShow();
                        } else {
                            self.$right.find('option, optgroup').mShow();
                        }
});
```

**Comment by crlcu** [comment]
You might be right,
So in case of multiple destinations, it seems that the right `search input` is filtering all the right `select` elements.

**Comment by danowar2k** [comment]
Ok, but this isn't the intended behaviour, if I understand you correctly. Good, I'll see what I can do...

**Comment by crlcu** [comment]
To keep it simple, I think current behaviour is just fine.
If someone will need at some point multiple `right` destinations with a `search input` foreach destination, then I might think introducing the feature.

**Comment by danowar2k** [comment]
OK. Will you update the docs and/or the examples so that the current behaviour is explained/shown?

**Comment by crlcu** [comment]
Yep,
I'll update http://crlcu.github.io/multiselect/examples/multiple-destinations.html once I have some free time.

**Comment by danowar2k** [comment]
Hm. Just a quick note: The way you prepend the search input just before the select element leads to the optical illusion that the input only filters the select directly below it (Between the select header and the select element). If the right search filter filters every select, it should probably be placed somewhere where it either implies that you use it for all right selects...or it should have some explicit info which elements the filter is for.

Just an opinion...
