### ISSUE TITLE
MoveUp/MoveDown: moving multiple options up or down doesn't work right

### ISSUE THREAD

**Issue by danowar2k** [crlcu/multiselect#121]
When you select multiple items and click "moveUp":
before:
0: "0"
1: "bla" 
2: "2"
3: "3"
4: "foo"
5: "5"

expected:
0: "bla"
1: "0"
2: "2"
3: "foo"
4: "3"
5: "5"

actual:
0: "bla"
1: "foo"
2: "0"
3: "2"
4: "3"
5: "5"

Vice versa with moveDown.

I don't know if this is wanted behaviour.

**Comment by crlcu** [comment]
Move up/down should work only with 1 selected option.

**Comment by danowar2k** [comment]
I just managed to allow the above behaviour. If you don't specifically forbid moving multiple options up and down, this would be in my big PR soon.

**Comment by danowar2k** [comment]
Just read the docs again:

"The button that move options from right side to the top". I'm unsure if this means that a selected option is moved to the top of the list, or that the selected option is moved one step further up.
