### ISSUE TITLE
Search very slow for dataset with >4000 options

### ISSUE THREAD

**Issue by sharath1907** [crlcu/multiselect#124]
Hi,

Search feature for datasets with >4000 options is super slow. Page becomes unresponsive :( 
Can we have an optimized search feature?

**Comment by crlcu** [comment]
This is because I have tried to provide support for IE and Safari, where hiding an `option` doesn't work as it should work.
I'll try to find a way to improve the search.

**Comment by alban-ameti** [comment]
Potential fix:

```
var isIE = false;
var isSafari = false;

$.fn.mShow = function() {
    this.removeClass('hidden').show(0);
    return this;
};

$.fn.mHide = function() {
    this.addClass('hidden').hide(0);
    return this;
};

$.expr[":"].search = function(elem, index, meta) {
    return $(elem).text().startsWith(meta[3]);
}
```

This is not going to work for everyone obviously and you lose the ability to regex the entries and support for IE and safari.

**Comment by jtl3d** [comment]
For what it's worth, detecting Chrome speeds up at least Chrome:
```
var isChrome = ua.toLowerCase().indexOf("chrome") > -1;
var isSafari = !isChrome && (ua.toLowerCase().indexOf("safari") > -1);
```
Thought I'd share for anyone not too worried about their IE/Safari users, but not wanting to alienate them completely.

**Comment by m0hamedessam** [comment]
any solution for Chrome? 
i think only firefox works fine i use 10k options

**Comment by raisou** [comment]
Hello, Any update on this one ?
