### ISSUE TITLE
Dynamically add content in the multiselect

### ISSUE THREAD

**Issue by apophys0** [crlcu/multiselect#127]
Hi,
I have been trying to dynamically fill the left side of the multiselect without much success:   the idea is to populate it depending on what the user chose in an independent select component.  Tried

`var value = "New value";`
`$('#multiselect').empty();`
`$('#multiselect').append("<option value=" + value + "> " + value + "</option>");`
`$('#multiselect').selectpicker('refresh');`

 The result was a completely new left select, size 1, with an unpredictable behaviour.
Any idea?

**Comment by crlcu** [comment]
Hi @apophys0 

You have an example [here](https://jsbin.com/muqajey/edit?html,css,output).
