### ISSUE TITLE
Allow to edit moveFromAtoB function

### ISSUE THREAD

**Issue by daffoxdev** [crlcu/multiselect#128]
Hi.

Can you please add this one to moveFromAtoB function

```js
if ( typeof self.callbacks.moveFromAtoB == 'function' ) {
    return self.callbacks.moveFromAtoB(self, $source, $destination, $options, event, silent, skipStack);
}
```

I added it for my copy now, but would be good if it would be added as native.

I used it to write deep optgroup logic. For my situation optgroup have 2 nesting levels. But HTML not allowing nesting optgroups that way, so I need to write logic for unique situations sometimes like this .

Thank you.

**Comment by crlcu** [comment]
Hi,
This is now available in [`v2.3.13`](https://github.com/crlcu/multiselect/releases/tag/v.2.3.13)
