### ISSUE TITLE
Unable to update lists on left and right side 

### ISSUE THREAD

**Issue by ikandarpa** [crlcu/multiselect#130]
Hi I am unable to find a way to  dyanamically add and remove items from left and right lists.
Is there a way to do this?

**Comment by crlcu** [comment]
It's as simple as appending options to a simple select element.

**Comment by ikandarpa** [comment]
i am opening the list in a popup window, after that i am unable to add/remove options from the lists.

**Comment by crlcu** [comment]
Please have a look at this [issue](https://github.com/crlcu/multiselect/issues/127).
There is an [example](https://jsbin.com/muqajey/edit?html,css,output) of how you can do that.
