### ISSUE TITLE
How to sort the left and right lists?

### ISSUE THREAD

**Issue by ikandarpa** [crlcu/multiselect#131]
how to sort left and right lists? when you move options to left and right and when initially loading?
also how do you write a custom sort function and how does it work?

**Comment by crlcu** [comment]
Hi @ikandarpa 

The `sort` function needs to be smth like this:

```javascript
sort: function(a, b) {
    if (a.innerHTML == 'NA') {
        return 1;
    } else if (b.innerHTML == 'NA') {
        return -1;
    }

    return (a.innerHTML > b.innerHTML) ? 1 : -1;
}
