### ISSUE TITLE
Custom sort: not working for right list

### ISSUE THREAD

**Issue by ikandarpa** [crlcu/multiselect#132]
the custom sort function works correctly when i move option to the left list,
but the sort doesn't work properly when i move option to the right as a result, the right list appears to be sorted in a random fashion, there is no rhyme and reason how it sorts on right, is there a way to fix this

**Comment by crlcu** [comment]
I have double checked the source code and is seems like everything is fine with sorting left/right sides.

Could you provide any examples pls ?
Maybe a pice of code.

**Comment by crlcu** [comment]
Please reopen the issue once you have some example code.
