### ISSUE TITLE
Search performance issue with suggested fix.

### ISSUE THREAD

**Issue by xbrady** [crlcu/multiselect#135]
On the following line there is a performance issue:
var $grpHide= self.$left.find('option.hidden').parent('optgroup').not($(":visible").parent()).mHide();

This selector is very slow as it traverses all elements in the dom:
$(":visible").parent()

If you change it to the following it should fix this issue:
var $grpHide= self.$left.find('option.hidden').parent('optgroup').not(":visible:parent").mHide();

This of course applies to the right side also.

**Comment by crlcu** [comment]
That doesn't seem to work, but I think that piece of code can be changed to:
```javascript
var $grpHide = self.$left.find('option').closest('optgroup').mHide();
var $grpShow = self.$left.find('option:not(.hidden)').parent('optgroup').mShow();
```

In this way we hide all the `optgroup`'s in the beginning, then we make visible only those that contains at least one `option` that's visible.

**Comment by crlcu** [comment]
I have released a new version - hope that will change a bit the speed of search.

**Comment by xbrady** [comment]
Thanks crlcu, I didn't think to test it with the optgroup settings enabled.

**Comment by xbrady** [comment]
I've confirmed that the latest build is working and is much faster than before. Thanks!
