### ISSUE TITLE
After using AJAX the filter functionality is not working anymore

### ISSUE THREAD

**Issue by PatrickScholten** [crlcu/multiselect#140]
It seems "$.expr[":"].search" is not hit. As workaround I use:

```
var $thisValue = this.value;
var $toShow = self.$left.find('option').filter(function(idx, el) {return el.text.indexOf($thisValue) !== -1}).mShow();
var $toHide = self.$left.find('option').filter(function(idx, el) {return el.text.indexOf($thisValue) === -1}).mHide();

---

var $thisValue = this.value;
var $toShow = self.$right.find('option').filter(function(idx, el) {return el.text.indexOf($thisValue) !== -1}).mShow();
var $toHide = self.$right.find('option').filter(function(idx, el) {return el.text.indexOf($thisValue) === -1}).mHide();
```

**Comment by crlcu** [comment]
Hi @PatrickScholten 

I have tried to reproduce this issue by going to http://crlcu.github.io/multiselect/examples/search.html and then from the console I have appended a new `option` like this:
```javascript
$('#search').append('<option value="new item" data-position="7">New Item</option>');
```
And then I have searched for `New Item` and it seems that the search was working as expected.
![image](https://user-images.githubusercontent.com/1661844/32485756-2cf5a2e0-c3ad-11e7-922f-9c73a49f155f.png)

Could you please tell me exactly why are you doing so I can probably spot out which is the isssue ?
