### ISSUE TITLE
reset or send all to left 

### ISSUE THREAD

**Issue by empitegayan** [crlcu/multiselect#142]
is there any way to reset or send all to left? any event or any hack? 

i try to do this way but still nothing happens 

```
var MS = $('.js-multiselect').data('crlcu.multiselect');        // grab the current Multiselect instance
var $options = $('.js-multiselect').children('.defaultColumn'); // grab all options of interest
MS.moveFromAtoB(MS.$right, MS.$left, $options);
```

**Comment by crlcu** [comment]
Hi @empitegayan,

Hope basically there's not an event to do that.
You can achieve this by doing something like this:

1. mark all items from `right` side as `selected`
2. trigger a click to the `move all to right` button
