### ISSUE TITLE
Selecting multiple items with 'Shift' button on Firefox

### ISSUE THREAD

**Issue by wardzinskim** [crlcu/multiselect#143]
The problem is only on Firefox browser.
In case of multiselect with search field. I search some elements and select them using shift button. 

![before](https://user-images.githubusercontent.com/9616234/33762850-7c51228c-dc0e-11e7-9428-46c44bef559e.png)

Next i remove text from search field and i got this:
![after](https://user-images.githubusercontent.com/9616234/33762861-81632964-dc0e-11e7-9c19-81a48d79f445.png)

**Comment by crlcu** [comment]
Thanks for pull request @wardzinskim
