### ISSUE TITLE
Right box item selection issues (when moved from left to right it should automatically selected)

### ISSUE THREAD

**Issue by dev22m** [crlcu/multiselect#145]
Hi crlcu,
I am using your multi select plugin and its look great.
But when i have implemented V2.4.0 after that when i m select item from left and move to right that time right side items not getting automatically selected. in V2.0 its automatically selected all items which we have moved from left to right.

So can you please help me in this.

**Comment by crlcu** [comment]
Hi @dev22m 

You can use the `afterMoveToRight: function($left, $right, $options) { do something here }`.
