### ISSUE TITLE
Question: How to return true/false to BeforeMoveToLeft/Right based on ajax request result

### ISSUE THREAD

**Issue by Frankosun** [crlcu/multiselect#146]
Hi, 

firstly thank you for this plugin, it is great! I would like to also ask you for the help. I am just trying to update based on movement of items between select fields the database list. I am using the ajax call within the BeforeMoveToLeft/Right event but i do not know how to return based on ajax result the true/false to the event in order to proceed/do not proceed the change in the selects. 

This is example of my code,please do you have an idea how to achieve it?

Thank you for any suggestion. 

`beforeMoveToLeft: function ($left, $right, $options) {
                        var nodeNames = [];
                        $.each($options, function (i, el) {
                            nodeNames[i] = {key: el.nodeName, value: el.value};
                        });
                        var postdata = JSON.stringify(nodeNames);
                        //var recursiveDecoded = decodeURIComponent($.param($options));
                        //alert(recursiveDecoded);
                        var results;
                        $.blockUI();
                        $.ajax({
                            url: 'delete_filter.php',
                            type: 'POST',
                            data: {
                                data: postdata
                            },
                            success: function (result) {
                            $.unblockUI();    
                                return true;
                            }
                        });
                        
                        
                    }`

**Comment by crlcu** [comment]
Hi @Frankosun 

Have you tried adding `async: false` to the `$.ajax({ ..., async: false })` ?

**Comment by Frankosun** [comment]
Hi @Crlcu, 

thank you for reply. I know about this possibility but i was interrested if there is still async possibility to achive this. Do you have some idea?

**Comment by crlcu** [comment]
Hi,
In this case, it seems to me like an `sync` request anyway.

**Comment by justin-dx** [comment]
Even after making the call synchronous and returning true, it fails to move the selected item to either select.

**Comment by Jogii** [comment]
I am facing similar issue when i am making service call while moving item from left to right or right to left. I understand BeforeMoveToLeft/Right needs return = true, but is there a feasibility to inject the same into the multiselect on success of the service call. Please help/Advise.
