### ISSUE TITLE
How do you preload elements on the left side and others on the right side beforehand?

### ISSUE THREAD

**Issue by martinmurciego** [crlcu/multiselect#150]
Greetings, I congratulate you for this component.
But since I recently started to try it, I want to consult you. Assuming that you read items from a database or some other source, maybe two arrays. Suppose that the first list would be menues of application and the second menu of user profile. How do you preload elements on the left side and others on the right side beforehand? In my case I use optgroup. Is there any way by javascript or by html that is convenient? Or is there some way to load elements in the first list and by javascript code to move certain elements to the other side maybe by value?

**Comment by crlcu** [comment]
Hi,

I would say the easiest way is:

1. For the left side, fetch from database all the menus that are not already assigned to the user

2. For the right side, fetch from database all the menu that are assigned to the user

Then everything will work.

You have a second option, for the left side fetch everything from db, and for the right side fetch what's assigned to the user - then `multiselect` plugin will automatically remove from the `left` side all the entries that match with the right side.
