### ISSUE TITLE
ignoreDisabled: true does not work with optgroups

### ISSUE THREAD

**Issue by ericenns** [crlcu/multiselect#152]
When using optgroups and rightAll or leftAll, all elements are being moved over even if they are disabled.

**Comment by oliveiraped** [comment]
Hi, as a possible workaround you could do this

$("#plugins_undo").attr('disabled','disabled');
$("#plugins_rightAll").attr('disabled','disabled');
$("#plugins_leftSelected").attr('disabled','disabled');
$("#plugins_leftAll").attr('disabled','disabled');
$("#plugins_redo").attr('disabled','disabled');

Disable the buttons.

Best 

Pedro
