### ISSUE TITLE
alphabetically sort only for options

### ISSUE THREAD

**Issue by Rockman1233** [crlcu/multiselect#157]
Hi! How could I make alphabetically sort only for options not for optgroup? tx

**Comment by Rockman1233** [comment]
I did it by jQuery
sort : function(a, b) {
            return ($(a).closest('option').text() > $(b).closest('option').text()) ? 1 : -1;
        },

**Comment by crlcu** [comment]
Hi @Rockman1233 

That's nice. I'm happy that you managed to find a solution for this query.
