### ISSUE TITLE
Add Icon to Option

### ISSUE THREAD

**Issue by NashBridgesAT** [crlcu/multiselect#161]
Hi
I would like to add a specific icon to the options in the multiselect fields. How can I do that? Can you help me?
Thx
Christian

**Comment by crlcu** [comment]
Hi @NashBridgesAT 

Keeping in mind that this plugin uses html `select`, `optgroup` and `option` attributes, I don't think this is possible.
Anyway, in case you find a way to have an icon displayed inside an `option` element without using a plugin, that should work for `multiselect plugin` as well.

**Comment by NashBridgesAT** [comment]
Hi @crlcu 
Thanks for your soon reply. Searching google for a solution the only way to do that would obviously be to use the unicode references of font-awesome characters for example. But i didn't made it work yet.
Actually i am trying to work with CSS, maybe i find a way, if so, i will post it here.
