### ISSUE TITLE
CDN services do not have the 2.5.1 version

### ISSUE THREAD

**Issue by ytliuSVN** [crlcu/multiselect#165]
Anybody can tell me if there is a [CDN](https://cdnjs.com/libraries/multiselect) for Multiselect **v2.5.1**? Thanks.

**Comment by crlcu** [comment]
Hi @ytliuSVN 
Seems that 2.2.9 is the latest version on https://cdnjs.com/libraries/multiselect - will try to find out why.
In the mean time you can use https://cdn.rawgit.com/crlcu/multiselect/v2.5.1/dist/js/multiselect.min.js
