### ISSUE TITLE
Can not retrieve data from left to right side.

### ISSUE THREAD

**Issue by DimitrisChrist** [crlcu/multiselect#172]
I want to ask something. If I retreive data from db oracle in jsp can not move to the other side. My data are only in left side. Can you suggest me any solution?
Thanks.

**Comment by crlcu** [comment]
Hi @DimitrisChrist,
Basically this plugin does not care to much about how you add your options to the left side.
As long as you have the right id's for your select elements, it should work.

**Comment by DimitrisChrist** [comment]
Unfortunately the problem is on data. I have all the data on the left side but when I press on of the buttons in the middle nothings happening. Can you help me?

**Comment by DimitrisChrist** [comment]
<div class="row">
                  <label class="col-xs-1 control-label">AUDITORS</label>
                  <div class="col-xs-3"> 
       <select name="Wauditorid[]" id="multiselect" multiple="multiple" size="7"class="form-control" > 
                            <%=auditors%>
                         
                        </select>
                  </div>
  <div class="col-xs-2">
      <button type="button" id="search_rightAll" class="btn btn-block"><i class="glyphicon glyphicon-forward"></i></button>
      <button type="button" id="search_rightSelect" class="btn btn-block"><i class="glyphicon glyphicon-chevron-right"></i></button>
      <button type="button" id="search_leftSelect" class="btn btn-block"><i class="glyphicon glyphicon-chevron-left"></i></button>
      <button type="button" id="search_leftAll" class="btn btn-block"><i class="glyphicon glyphicon-backward"></i></button>
  </div>
                            
       <div class="col-xs-3">
           <select name="Wauditorid[]" id="multiselect" class="form-control" size="7" multiple="multiple"></select>
                          
          </div>        
                </div>

**Comment by DimitrisChrist** [comment]
<div class="row">
                  <label class="col-xs-1 control-label">AUDITORS</label>
                    
                    <div class="col-xs-3"> 
                        <select name="Wauditorid[]" id="multiselect" multiple="multiple" size="7"class="form-control" > 
                            <%=auditors%>
                         
                        </select>
                  </div>
  <div class="col-xs-2">
      <button type="button" id="search_rightAll" class="btn btn-block"><i class="glyphicon glyphicon-forward"></i></button>
      <button type="button" id="search_rightSelect" class="btn btn-block"><i class="glyphicon glyphicon-chevron-right"></i></button>
      <button type="button" id="search_leftSelect" class="btn btn-block"><i class="glyphicon glyphicon-chevron-left"></i></button>
      <button type="button" id="search_leftAll" class="btn btn-block"><i class="glyphicon glyphicon-backward"></i></button>
  </div>
                            
       <div class="col-xs-3">
           <select name="Wauditorid[]" id="multiselect" class="form-control" size="7" multiple="multiple"></select>
                          
          </div>        
                </div>

**Comment by crlcu** [comment]
Hi @DimitrisChrist,

As I've expected, you are not initialising the multiselect in the right way.
Please have a look at the documentation and make sure you follow the instructions.
