### ISSUE TITLE
Add new event for initialization completion

### ISSUE THREAD

**Issue by set-webmaster** [crlcu/multiselect#178]
Hi there, quick question. Would it be possible to trigger an event when the initialization is complete?

**Comment by set-webmaster** [comment]
Nevermind I found the `startup` option by reading more carefully. 
Sorry for bothering :)

**Comment by set-webmaster** [comment]
Reconsidering it, it might still be useful to add a simple event just to notify other parts of a page that the multiselect is initialized. As otherwise, I need to overwrite the default function completely simply to add the event. What do you think of it?

**Comment by crlcu** [comment]
Hi @set-webmaster 

I'm not sure I understand what you need atm.
Is `afterInit` not what you are looking for?
If not, could you detail a bit more what/when do you need that event to happen - maybe you can put some example code or make a PR?

E.g.: from https://github.com/crlcu/multiselect/blob/master/dist/js/multiselect.js
```javascript
// Append left filter
if (self.options.search && self.options.search.left) {
    self.options.search.$left = $(self.options.search.left);
    self.$left.before(self.options.search.$left);
}

// Append right filter
if (self.options.search && self.options.search.right) {
    self.options.search.$right = $(self.options.search.right);
    self.$right.before($(self.options.search.$right));
}

// Initialize events
self.events();

// TODO: I want another event to happen here

if ( typeof self.callbacks.afterInit == 'function' ) {
    self.callbacks.afterInit();
}
```

**Comment by set-webmaster** [comment]
Yeah as I said in the previous post just before closing, it can effectively be used for what I was looking for. I was just thinking it might be useful to trigger a native multiselect event when init is complete so that any code that is not directly related to its initialization can be notified that it has completed iinitialization. 

But, this can also be done within the `afterInit` callback, it's just that it has to always be specified while it could be done by default.
