### ISSUE TITLE
TypeError: $(...).find(...).multiselect is not a function

### ISSUE THREAD

**Issue by lidak** [crlcu/multiselect#18]
Try to use your plugin insight my angular app and get an error during init.

**Comment by crlcu** [comment]
Hi @lidak 

Could you please put some example code ?

**Comment by lidak** [comment]
Sure. https://github.com/lidak/multiselect-issue

**Comment by crlcu** [comment]
Well,
It looks like the selector is not ok.

```javascript
$(element).find('multiselect').multiselect();
```

This should be

```javascript
$(element).find('#multiselect').multiselect();
```

or

```javascript
$(element).find('.multiselect').multiselect();
```

as you element looks like

```html
id="multiselect" class="multiselect
```

**Comment by crlcu** [comment]
Please let me know if that fixed your issue.

**Comment by lidak** [comment]
I changed selector but it didn't help.

**Comment by lidak** [comment]
Does multiselect require bootstrap.js? (Thank you for helping)

**Comment by crlcu** [comment]
No. It only requires jQuery.
I have tried something like $(document).find('#multiselect').multiselect(); and it works fine.

I think you must double check if your #multiselect is there when you initialize them.
Maybe try to 
```javascript
console.log($(element).find('#multiselect'));
```
and see if the result is as you expected.
