### ISSUE TITLE
Performance slow when Transfering dataset to right and to left > 4000

### ISSUE THREAD

**Issue by irel2629** [crlcu/multiselect#183]
My browser hangs and it take 22 seconds to transfer my data set to right estimated data count 4000 please help thank you.

**Comment by crlcu** [comment]
Hi,

I’m not sure what’s the best approach for fixing your issue, but allowing the user to do something with 4k items at a time in the UI doesn’t sound like the best idea.

I’m happy to change the plugin if there’s a way we can make it work faster with such amount of data so in case you have any suggestions please let me know.

**Comment by irel2629** [comment]
Hi sir,

Yes i know its not a good idea moving 4k dataset at a time but it is how the lazy user do it specially in filtering reports in our web app. i set up the multiselect ui in a tab so the user can filter the categories and generate the report after selecting some products which is on our last tab. see screenshot below.

i am thinking if we can enhance the js execution time when transferring large amount of data from left to right vice versa. 

![image](https://user-images.githubusercontent.com/57520074/68459671-f5030600-0240-11ea-8ba3-7bb842c492a0.png)

**Comment by crlcu** [comment]
Hi @irel2629 

I haven't managed to find a good solution to your issue.
One idea might be to limit the amount of items that can be selected at a time to 1000 for example and disable the move all buttons.
