### ISSUE TITLE
Keep rendering sort doesn't work

### ISSUE THREAD

**Issue by bcaly** [crlcu/multiselect#185]
Hi, 

It sounds that keep rendering sort doesn't work.

If you try on this exemple : https://crlcu.github.io/multiselect/examples/keep-rendering-sort.html
the options keep the same order that the original select.

After some research, it seems to come from this part : 
```
if ( typeof self.callbacks.sort.right == 'function' && !silent && !self.doNotSortRight ) {
                    self.$right.mSort(self.callbacks.sort.right);
}
```
`doNotSortRight` is not defined, to fix it on my project I set `doNotSortRight` with `self.options.keepRenderingSort`

**Comment by crlcu** [comment]
Hi @bcaly 

The original values are:
![image](https://user-images.githubusercontent.com/1661844/71584613-06b7aa00-2b1c-11ea-8b34-dc55c4e47ce8.png)

After moving them to the right, no matter which item is moved first, the options on the right are
![image](https://user-images.githubusercontent.com/1661844/71584628-218a1e80-2b1c-11ea-8d48-a58fd0a04997.png)

So they have the same order as when the options were rendered to the page - which is what `keepRenderingSort` is meant to do.

In case you think there is a bug, please reopen the case and provide a few replication steps.
