### ISSUE TITLE
Not rendering under IOS Plateform

### ISSUE THREAD

**Issue by maamirh** [crlcu/multiselect#191]
I am using Aurelia Framework and i use "multiselect-two-sides" in my project .This is working under Microsoft OS ,Chrome and in all browsers but not working properly under iOS platform.

I did many search for fixing this issue because many other users reported this issue.

Recently i used this code to fix my problem but its also not working .

```
if (navigator.userAgent.match(/(iPod|iPhone|iPad)/i)) {
      $('select[multiple]').each(function () {
        var select = $(this).on({
          "focusout": function () {
            var values = select.val() || [];
            setTimeout(function () {
              select.val(values.length ? values : ['']).change();
            }, 1000);
          }
        });
        var firstOption = '<option value="" disabled="disabled"';
        firstOption += (select.val() || []).length > 0 ? '' : ' selected="selected"';
        firstOption += '>&laquo; Select ' + (select.attr('title') || 'Options') + ' &raquo;';
        firstOption += '</option>';
        select.prepend(firstOption);
      });
    }
```
This is working fine under Windows 10 ,Chrome
![image](https://user-images.githubusercontent.com/46965638/73072271-97dd2f00-3ed6-11ea-9aa8-a40eb7ec2d9a.png)

This is the screenshot under iPhone ,which is showing 0 Items 
![image](https://user-images.githubusercontent.com/46965638/73072396-c955fa80-3ed6-11ea-89b1-e1d9e9a9069b.png)

This is screenshot under iPhone after using above code.

![image](https://user-images.githubusercontent.com/46965638/73072445-e4c10580-3ed6-11ea-94e5-d1ff9bc869fd.png)

I think this is plugin bug and should be fix

**Comment by crlcu** [comment]
Hi @maamirh 

You are more than welcomed to create a pull-request for this issue.
