### ISSUE TITLE
Right collection is cleared in Edge (Dev)

### ISSUE THREAD

**Issue by vfabregat** [crlcu/multiselect#192]
Hello!

I've found a wrong behavior in edge dev (the based on chromium). I know the most of the users don't use the Dev version, but could be something that can be used in production in a near future.

In production version, is working correctly.

### Repro steps

- Go to the sample web (https://crlcu.github.io/multiselect/examples/zero-configuration.html)
  - The first difference, in chrome I can see all items, in edge only see two 4 and 5. Sometimes all are loaded, after press F5 the error is reproduced.
- Double click in any item at the left
  - The item is passed to the right
- Double click in another item at the left
  - the item is passed to the right but the previous item was removed from the list

### Environment
- Windows 10 
- Microsoft Edge - Version 81.0.403.1 (Official build) dev (64-bit)

**Comment by danday74** [comment]
reproduced this issue today in our production environment - must have been a Chrome update - any ideas how to fix?

**Comment by tom-diacono-WL** [comment]
+1 for this issue. This morning someone reported this behaviour to me within our application. I tested it, and couldn't reproduce. They were on Chrome 81, as opposed to my Chrome 80. I updated to Chrome 81, and the issue instantly manifested.

Possibility that the Chromium version on my version of Chrome is similar to the version you are running on Edge?

**Comment by vfabregat** [comment]
No, no idea... Because was on Dec version I didn't do anything. If you found a solution please let me know

**Comment by mgol** [comment]
This is most likely #194. The fix was released to stable Chrome in 81.0.4044.138, other Chromium-based browsers should follow shortly.
