### ISSUE TITLE
Chrome browser compatibility issue

### ISSUE THREAD

**Issue by ssboopathi1991** [crlcu/multiselect#193]
browser compatibility. I have used on the last 6 months this plugin. It's working fine. Recently I have updated the chrome browser(V 81.0.4044.113). This version, select option not working properly.

EG: 
The first time, I have chosen on 2 items and choose the drag option - left to right, it's moved.
The second time, I have chosen 1 item and choose the drag option - left to right, it's moved. 
But first 2 items hidden, second 1 item showing.

In the same scenario, I have tried multiple times. Same response, we got it. 

I have checked left to right & right to left - I phased on the same issue.

But I have checked on chrome(80.0..) lower version, it's working fine.

**Comment by mgol** [comment]
This is most likely #194. The fix was released to stable Chrome in 81.0.4044.138, other Chromium-based browsers should follow shortly.
