### ISSUE TITLE
The mSort function seems to get broken in Chromium / Chrome 81.0.4044.113 (Official Build) (64-bit) and later

### ISSUE THREAD

**Issue by lyubomyr-shaydariv** [crlcu/multiselect#194]
Long story short and SSCCE:

```html
<html>
<head>
<title>jquery multiselect Chrome 81 bug</title>
<script src="jquery-3.5.0.min.js"></script>
<script src="multiselect.min.js"></script>
<script>
        $(document).ready(function() {
                $("#src").multiselect({
                        //sort: false
                });
        });
</script>
</head>
<body>
<h1>jquery multiselect Chrome 81 bug</h1>
<select id="src" size="5" multiselect="multiselect">
        <option>9</option>
        <option>3</option>
        <option>2</option>
        <option>4</option>
</select>
<select id="src_to" size="5" multiselect="multiselect">
</select>
</body>
</html>
```

In the code above the `option` elements sequence is expected to sort from (9, 3, 2, 4) to (2, 3, 4, 9). This seems to work fine in previous Chrome versions or the current version of Firefox. In Chrome  81.0.4044.113 (Official Build) (64-bit) the selects go crazy if the sorting function is defined: (3, 9) is only available and the rest of the `option` elements are only rendered when moving elements from one select to another.

Narrowing down to the code, it seems that something's going wrong with the way the plugin reappends sorted nodes to the DOM https://github.com/crlcu/multiselect/blob/a916984bd1c22e9e3c64264618f00e656a85a54b/dist/js/multiselect.js#L785 and https://github.com/crlcu/multiselect/blob/a916984bd1c22e9e3c64264618f00e656a85a54b/dist/js/multiselect.js#L792.

The issue is similar to the issues decribed in #192 and more recent #193 and #195.

EDIT

I've just rechecked the issue in the latest dev Chromium 84.0.4122.0 (Developer Build) (64-bit) and it's reproducible there too.

**Comment by lyubomyr-shaydariv** [comment]
It looks like jQuery is to blame: removing the jQuery-driven DOM manipulation in favor of direct DOM manipulation seems to work. I don't think that the plugin has to be fixed itself, and the `$.fn.mSort` method should be patched on-fly after the plugin is loaded. Once jQuery is fixed, the on-fly patch shold be removed. The following code seems to work for me:

```js
// chrome81+jquery3xxfix.js
(function($) {

        $.fn.mSort = function(callback) {
                var children = this
                        .children()
                        .sort(callback);
                for ( var j = 0; j < this.length; j++ ) {
                        for ( var i = 0; i < children.length; i++ ) {
                                this[j].appendChild(children[i]);
                        }
                }

                this
                        .find('optgroup')
                        .each(function(_, group) {
                                var children = $(group).children()
                                        .sort(callback);
                                for ( var i = 0; i < children.length; i++ ) {
                                        group.appendChild(children[i]);
                                }
                        });

                return this;
        };

})(jQuery);
```

**Comment by dmethvin** [comment]
Can you direct me to the documentation and implementation for the `.sort()` method being used there?

**Comment by lyubomyr-shaydariv** [comment]
@dmethvin the `sort` method is native. I've just re-checked if the issue is reproducible without the plugin and the following code can produce the same (assuming the plugin is not even loaded and jQuery is the only external component):

```js
$(document).ready(function() {
        const parent = $("#src");
        parent.children()
            .sort((e1, e2) => e1.innerHTML.localeCompare(e2.innerHTML))
            .appendTo(parent);
});
```

Interestingly, removing the `sort` call renders empty `select`. However, if the document-ready callback code is put in the `script` element after the `select`, the `select` children get order in expected order.

Test case: https://jsfiddle.net/2yzneg8d/

**Comment by dmethvin** [comment]
That `.sort()` method is on a jQuery object, not a native Array. If it has not been replaced by a plugin it is [this one](https://github.com/jquery/jquery/blob/3.3.1/src/core.js#L118-L122). Just wondering why it's being used. As the comment there says, it is for internal use and doesn't behave like a jQuery method. In particular, the native method does not return the thing it sorted, it just sorts the array in place.

**Comment by lyubomyr-shaydariv** [comment]
@dmethvin ah, now I see that I've been confused with the output of `console.log(this.children().sort)` -- this made me think it's native.

If the `sort` method is for internal use only and there is no documentation at `https://api.jquery.com/sort/`, was the `sort` public years ago? For example, I can see people using it for the same purposes: https://stackoverflow.com/questions/13490391/jquery-sort-elements-using-data-id .

Also, what does the `arr.sort` do that it breaks Chrome only?

**Comment by lyubomyr-shaydariv** [comment]
@dmethvin Not sure but it looks like omitting the `sort` method call makes Chrome render an empty select box. Is

```js
const parent = $("#src");
parent.children().appendTo(parent);
```

legal in jQuery?

**Comment by mgol** [comment]
@lyubomyr-shaydariv
> ```js
> const parent = $("#src");
> parent.children().appendTo(parent);
> ```

This should work. I tested locally on a few examples and it behaved as expected both with jQuery from `master` & from the `3.x-stable` branch.

> ah, now I see that I've been confused with the output of `console.log(this.children().sort)` -- this made me think it's native.

That's because this method is borrowed from `Array.prototype`. However, it wasn't exposed on purpose (back in the days we didn't have a good module system so everything had to be attached to the jQuery object) & it will be gone in jQuery 4.0. It's already gone in the 4.0 git builds: https://code.jquery.com/jquery-git.js

**Comment by mgol** [comment]
BTW, by "behaved as expected" above I meant that the elements were properly inserted as children of the select element. This looks like a Chrome bug; it should be possible to extract a native test case & report an issue in the Chromium bug tracker.

**Comment by mgol** [comment]
Looks like an issue has already been reported: https://bugs.chromium.org/p/chromium/issues/detail?id=1072475

**Comment by lyubomyr-shaydariv** [comment]
@mgol that's interesting, thank you. I'd like to know: does jQuery do something special behind the scenes while manipulating the DOM? Why I'm asking it is that when I replace the `appendTo` method with pure JavaScript and DOM, it seems to work perfectly in Chrome 81+.

**Comment by mgol** [comment]
I uploaded a test case with no libraries to the Chromium issue that does something like what jQuery does under the hood: https://codepen.io/mgol/pen/eYpBqMy

It requires first appending nodes to a document fragment and only then to the select wrapper.

**Comment by lyubomyr-shaydariv** [comment]
@mgol
> It requires first appending nodes to a document fragment and only then to the select wrapper.

So, this is why my fragment-less workaround works, and jQuery uses fragments behind the scenes. Am I right?

**Comment by mgol** [comment]
@lyubomyr-shaydariv Yes, I suspect that's why.

**Comment by lyubomyr-shaydariv** [comment]
@mgol now I see it clear, thank you!

**Comment by lyubomyr-shaydariv** [comment]
So the overall conclusion with help by @mgol is as follows:

- it's a Chromium bug causing DOM fragments manipulation regression;
- the select/optgroup/option elements seem to be only revelant;
- quick-fixes/patches that do not use DOM fragments but manipulate DOM nodes directly may be a work around;
- no fixes regarding the issue are expected either for this component, or jQuery.

I'll track the Chromium bug, and if the component dev members don't mind, I'd like to close this issue once Chromium gets fixed.

Thank you again @mgol !

**Comment by Chaitwo** [comment]
@lyubomyr-shaydariv Hey, Thank you for your insight on the sorting functionality. I haven't disabled sorting specifically in my multi-select and since the default value is true it is enabled and I like to keep it that way. So I've replaced the sort function in multiselect.js with your function and it seems to be working great as it was in chrome v80 or below versions. The left, right, and bottom buttons are working as they should but the top button is behaving irregularly as when I try to move an item to top the DOM issue occurs again. Is there a quick fix for this? or do I need to wait till the chromium devs fix the issue and release a new version? Thanks a ton for your help.

and here is the function I've replaced in multiselect.js file

```
$.fn.mSort = function(callback) {
        this
            .children()
            .sort(callback)
            .appendTo(this);

        this
            .find('optgroup')
            .each(function(i, group) {
                $(group).children()
                    .sort(callback)
                    .appendTo(group);
            })

        return this;
    }; 

```
with the code, you mentioned [here ](https://github.com/crlcu/multiselect/issues/194#issuecomment-617449890).

**Comment by lyubomyr-shaydariv** [comment]
@Chaitwo 

> Is there a quick fix for this?

No idea. My fix only replaces the multiselect component sort method code that uses jQuery under the hood in favor of direct DOM manipulation just because I'm using the multiselect component very limitedly with the reduced set of buttons.

>  or do I need to wait till the chromium devs fix the issue and release a new version? 

No idea either. Michał provided a real SSCCE (mine is not), and the very reason of the issue is how Chromium handles DOM fragments since v81 jQuery relies on heavily. I don't know if the Chromium fix is in real progress and what's the date it might be released, so I'd just suggest you to drill down your case in the multiselect component where it might use jQuery-driven DOM manipulation and try to replace that code with native DOM usage.

BTW, I didn't modify the original source of the multiselect plugin. I just supplied a monkey-patch file to be loaded right after the jQuery plugin so that it overrides its `mSort` function in runtime. Once the fixed version of Chrome (not Chromium) is released, I'm going to delete the monkey-patch file from my codebase as the Chromium regression would be gone.

**Comment by Chaitwo** [comment]
@lyubomyr-shaydariv Got it. Thank you for the quick reply. I'll try to drill down my case in the component and see what's going on. 

> Once the fixed version of Chrome (not Chromium) is released

Quick question. In your experience, how many days or weeks will it take for the devs to release a hotfix or a new fixed version?

Thanks again for the help.

**Comment by lyubomyr-shaydariv** [comment]
@Chaitwo well, I'm not a Chromium dev and never track the defects resolving velocity, but this https://www.chromestatus.com/features/schedule might be helpful. Also, the bug report tells it is tagged with Target-81, Target-83, Target-84, so it might be fixed within v81 with a minor update soon if I understand the meaning of tags correctly. But again, I'm not a Chromium dev and I'm not aware of their development process, so I don't want to mislead you.

**Comment by Chaitwo** [comment]
@lyubomyr-shaydariv Awesome. Thank you very much for the info.

**Comment by mgol** [comment]
One jQuery-based workaround is to attach the options to a different off-screen select & then append back to the original one after first forcing the layout: https://jsfiddle.net/bj7ud2v5/7/
Code also below for posterity:
```js
$(function() {
  const dummySelect = $('<select>');
  const select = $("#src");
  dummySelect.append(select.children());
  select.css('height'); // trigger the select layout
  dummySelect.children().appendTo(select);
});
```

**Comment by Chaitwo** [comment]
@mgol Thanks a ton for the help. I just added your piece of code in my `afterMoveUp`  function and it works like a charm.

I just tweaked it because once I use the moveUp button all the items below my selected item are getting selected and when I keep clicking the up button I just want to move my selected item to the top without the items under it.

```
    let topItem = $("#src").val()[0];
    $("#src").val(topItem);
```

Thanks again for your help.

**Comment by ghardy2k** [comment]
> It looks like jQuery is the cause: removing the jQuery-driven DOM manipulation in favor of direct DOM manipulation seems to work. I don't think that the plugin has to be fixed itself, and the `$.fn.mSort` method should be patched on-fly after the plugin is loaded. Once jQuery is fixed, the on-fly patch should be removed. The following code seems to work for me:
> 
> ```js
> // chrome81+jquery3xxfix.js
> (function($) {
> 
>         $.fn.mSort = function(callback) {
>                 var children = this
>                         .children()
>                         .sort(callback);
>                 for ( var j = 0; j < this.length; j++ ) {
>                         for ( var i = 0; i < children.length; i++ ) {
>                                 this[j].appendChild(children[i]);
>                         }
>                 }
> 
>                 this
>                         .find('optgroup')
>                         .each(function(_, group) {
>                                 var children = $(group).children()
>                                         .sort(callback);
>                                 for ( var i = 0; i < children.length; i++ ) {
>                                         group.appendChild(children[i]);
>                                 }
>                         });
> 
>                 return this;
>         };
> 
> })(jQuery);
> ```

thanks, this worked perfectly.  now, if i can ever remember to take this out when they fix the problem.

**Comment by mgol** [comment]
The fix was released to stable Chrome in 81.0.4044.138, other Chromium-based browsers should follow shortly.

**Comment by lyubomyr-shaydariv** [comment]
@mgol Thanks for the good news!

@crlcu I'll close the issue once I successfully double-check it reverting my "mSort"-patch on my workstation today.

**Comment by lyubomyr-shaydariv** [comment]
@Chaitwo, @ghardy2k (and maybe @rafalglowacz, @afzafri)
If you guys are using the patch, you can now remove it from your codebase if it's applied as the latest Chromium version is out and I can confirm that the patch is no longer necessary since Chromium 81.0.4044.138.

CC: @crlcu
