### ISSUE TITLE
Move up Issue (chrome)

### ISSUE THREAD

**Issue by zgelici** [crlcu/multiselect#195]
Hello,

I use Chrome Browser

 Recently i have issues with move_up button.

https://crlcu.github.io/multiselect/examples/move-up-down.html

if i use here the up button, it disappear. Than i click in the box. The option get showed.

Any idea, how i can fix this?

Looks like an render issue

**Comment by Chaitwo** [comment]
@zgelici I'm having the same issue and looking for a quick fix. If you find an answer can you share the solution here? Thanks!

**Comment by sukumar-smart** [comment]
Hello guys,
This may be a quick fix or this may helpful for you.
I added the focus event in it. after move up function the focus event is called.

Here is code : 
afterMoveUp: function(t) {**document.getElementById("multiselect_to").focus();**},

i added this in multiselect.js file.

**Comment by zgelici** [comment]
@sukumar-smart thanks for sharing your solution.
