### ISSUE TITLE
not rendering the listbox correctly 

### ISSUE THREAD

**Issue by ghardy2k** [crlcu/multiselect#197]
this started happening recently...maybe a week or two ago?   when the page loads, not all the select options are showing up.  even on your page at https://crlcu.github.io/multiselect/examples/javascript-options.html.   so the with data options, or javascript, you can see once you start clicking items around, then all of a sudden, more items pop up in the "from" list. 

 using google chrome version 81.0.4044.129 (Official Build) (64-bit)

**Comment by ghardy2k** [comment]
my manager tried this, and it works fine on his machine.  also, this works fine for me in firefox.  just not the new Edge or Chrome.  Also, if I am in Chrome, and resize to hit a different media breakpoint, the list will populate.

**Comment by luansieversHRd** [comment]
Also happening for me.

**Comment by luansieversHRd** [comment]
This example from the component shows the error: https://crlcu.github.io/multiselect/examples/move-up-down.html

**Comment by crlcu** [comment]
See #194 - feels like is the same root cause

**Comment by luansieversHRd** [comment]
Adding `keepRenderingSort: true,` solves the problem for me

**Comment by ghardy2k** [comment]
the fix is in the post https://github.com/crlcu/multiselect/issues/194       there is a replacement code for the jquery mSort function.  put in the bottom of my layout file, and all my dual selects work again.
