### ISSUE TITLE
Dynamic Data

### ISSUE THREAD

**Issue by trumboosahil** [crlcu/multiselect#20]
How to bind it with data which I get from Ajax Call

**Comment by crlcu** [comment]
Once you append the ``options`` to ``select`` element everything should work fine.

**Comment by crlcu** [comment]
For example go to http://crlcu.github.io/multiselect/ and in ``Chrome's Dev Tools Console`` put this:

```javascript
$('#multiselect').append('<option value="6">Item 6</option>');
```

Then move ``Item 6`` to right and left to see how is working.
