### ISSUE TITLE
How to get all the options moved to right on search?

### ISSUE THREAD

**Issue by Chaitwo** [crlcu/multiselect#203]
Hi,

I have a scenario where I need all the options on the right side box instead of the ones I've filtered without removing the filter. 

When there is a filter the options which are not showed in the right box are enclosed in a span tag. and the .options is only giving me the option values and not the options in the span.

So, my question is Can I get all the options (from the below Image I need all 7 options instead of 1)?

![options](https://user-images.githubusercontent.com/44081652/91277226-2a60ec00-e7a0-11ea-9019-5bb3adb0474c.PNG)

**Comment by crlcu** [comment]
Hi @Chaitwo 

Have you tried ?
```javascript
$("#multiMarket_to").find('span option');
```

**Comment by Chaitwo** [comment]
@crlcu It worked like a charm, Thanks a ton for the quick reply.

**Comment by crlcu** [comment]
No worries, have a good day.
