### ISSUE TITLE
How to programmatically move items?

### ISSUE THREAD

**Issue by schmidtl4** [crlcu/multiselect#207]
I have five multiselect instances on a page.  When the initial page is rendered, certain items (some in each instance) are assigned a distinct class.  I want to give the user the option (via a checkbox) to programmatically move all the items with the class to the corresponding right side using jquery/javascript (vs refreshing the page).  Is this possible? how?

**Comment by crlcu** [comment]
You have to think of it as being a normal select element and just write a custom function to move items from one side to another.
The other option would be to trigger the selected state for the required options then trigger the click action to the move left or right button.
