### ISSUE TITLE
Limit selected options

### ISSUE THREAD

**Issue by hossam-abdelmajeed** [crlcu/multiselect#213]
How I can limit the select options, either the Right side or Left side?

**Comment by crlcu** [comment]
Hi,
I think you can achieve this by using the beforeMoveRight / beforeMoveLeft callbacks.

**Comment by hossam-abdelmajeed** [comment]
may I ask for an example (full example), as I didn't found anything but a description in the documentation? 
much appreciated

**Comment by hossam-abdelmajeed** [comment]
a very simple code didn't work:
`beforeMoveToRight: function($left, $right, $options) { alert($options); return true; },`
any suggestions?

**Comment by jonth93** [comment]
I needed to limit the amount of options being move to the `$left` column. This worked for me:

`beforeMoveToLeft: function($left, $right, $options) {
                if($left.children('option').length >= 2) {
                    return false;
                } else {
                    return true;
                };
            }`

Also `$options` is an object. Putting it in an alert will only tell you `[Object object]`.
`console.log($options);` will show you what's in the object.

Hope it helps.
