### ISSUE TITLE
documentation : needs update ( moveToLeft and  moveToRight not in option list)

### ISSUE THREAD

**Issue by bleuscyther** [crlcu/multiselect#22]
**moveToLeft** and  **moveToRight** are  not mentionned  in option list but are used in **Multiple destinations** example.

Also its not clear what the callBack parameter stand for : 
* Multiselect, 
* options 
* event 
* silent 
* skipStack

Nice plugin by the way, i am trying to port this to angullar.

**Comment by crlcu** [comment]
Hi @bleuscyther 
I have added some documentation for ``moveToRight`` and ``movoToLeft``. Hope that helps.

**Comment by bleuscyther** [comment]
Perfect, Thx @crlcu
