### ISSUE TITLE
Can there be more than one on the same form?

### ISSUE THREAD

**Issue by toomanyjoes** [crlcu/multiselect#224]
I have a use case where I need 3 or 4 of these on the same form. Before I give it a test I just wanted to ask someone that might already know if this is possible with this library?

**Comment by crlcu** [comment]
Yes, you can have as many as you want.

**Comment by toomanyjoes** [comment]
@crlcu any idea how this can be done? When I change the ids from "multiselect" "multiselect_to" to say "multiselect1" "multiselect1_to" it no longer works.

Also of course changing the JS code to reflect the id change 
```
  $(document).ready(function() {
    $('#multiselect1').multiselect();
     .
     .
     .
```

**Comment by toomanyjoes** [comment]
Nevermind I see the issue, I also have to rename the buttons to reflect the name change.
