### ISSUE TITLE
Options in the source multiselect list are auto-selected and POSTed to the server when form is submitted

### ISSUE THREAD

**Issue by mstralka** [crlcu/multiselect#24]
I have this plugin enabled on a `select` field named `from_topics[]`, which has about 200 `<option>` elements.  The `select` element on the right is named `topics[]`.  When I press the form's submit button, all of the options are selected (even though they were not moved to the right), and therefore the POST to the server includes all of these values, which is not desired. 

To work around this, I have to use jQuery to intercept the form submission event and de-select them:
````
$('#topics_from').closest('form').submit(function(e) {
  // hack to de-select the options in the source list so they are not submitted to the server
  $('#topics_from option').prop('selected', true);
});
````

I don't think the option elements in the source list should be selected when the submit button is pressed.
Thanks

**Comment by mstralka** [comment]
Looking through `multiselect.js`, I see that this is its intended behavior, although I think it should at least be an option that can be turned off:

````
self.right.closest('form').on('submit', function(e) {
    self.left.children().prop('selected', true);
    self.right.children().prop('selected', true);
});
````

Maybe there could be an option that would disable this:
````
// My JS code
$('#from_topics').multiselect({
    //... existing options
    submitAllLeft: false, // true by default for backwards compatibility
    submitAllRight: false // true by default for backwards compatibility
});
````
````
// multiselect.js
self.right.closest('form').on('submit', function(e) {
    if (self.options.submitAllLeft) {
        self.left.children().prop('selected', true);
    }
    if (self.options.submitAllRight) {
        self.right.children().prop('selected', true);
    }
});
````

**Comment by crlcu** [comment]
Hi @mstralka 
Thanks for your suggestions. I'll do the changes today.

**Comment by crlcu** [comment]
Hi @mstralka 
Changes are now in master. v2.1.3 released

**Comment by mstralka** [comment]
Super thank you
