### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by AVSYS-AK** [crlcu/multiselect#26]
hi,

I downloaded latest release but could not find the search box for multiselect.

is it removed.?

**Comment by crlcu** [comment]
Hi @AVSYS-AK 
I have just double checked the latest release and the search functionality is there.
Is this example http://crlcu.github.io/multiselect/#demo-search working for you ?
If not, could you please provide me some code to check what's wrong ?

Thanks.

**Comment by AVSYS-AK** [comment]
Oops!

Its not working in Safari (Version 9.0.1 (11601.2.7.2)). Working fine in Chrome n Firefox.

Is it only me ? :(

**Comment by crlcu** [comment]
Ah,
Ok - I'll have a look then and let you know as soon as I have a resolution.

**Comment by AVSYS-AK** [comment]
Cool :)

**Comment by AVSYS-AK** [comment]
I have implemented search functionality and it is acting weird.
If i search for 'k', i am getting 'Haskell' but when i try typing 'j', it returns nothing .. while there are records like 'java'

I have created a fiddle [https://jsfiddle.net/ac6qbnw8/] (https://jsfiddle.net/ac6qbnw8/)

**Comment by crlcu** [comment]
It is case sensitive.

**Comment by AVSYS-AK** [comment]
Really sorry.. i am a noob..

The search is case sensitive... can you suggest how to make it regex search?

**Comment by crlcu** [comment]
Easiest way is:

```javascript
if (option.text.toLowerCase().indexOf(search.toLowerCase()) > -1) {
...
}
```

**Comment by AVSYS-AK** [comment]
@crlcu Thanks for the help :)

**Comment by crlcu** [comment]
Or if you prefer regex:
```javascript
var regex = new RegExp(search,"ig");            
if (option.text.search(regex) >= 0) {
...
}
```

**Comment by AVSYS-AK** [comment]
@crlcu hey, did you find a fix for search not working in Safari ?

**Comment by crlcu** [comment]
hi @AVSYS-AK 
No, I didn't managed to do that yet.

Sorry

**Comment by crlcu** [comment]
Do you have any suggestions ?

**Comment by AVSYS-AK** [comment]
for the moment, I'm executing search on enter key hit... lets see if that works.
