### ISSUE TITLE
Using Ajax to Re-populate the Select List

### ISSUE THREAD

**Issue by rgalpin** [crlcu/multiselect#28]
I am using ajax to change the contents of the SELECT list options in the left side when a radio button is selected. I am successfully returning a new SELECT list to the multiselect without reloading the page. However, the list is dead. I am unable to get items to move from left to right. Also the list does not react to the Search entry. It seems like I need to re-initialize the multiselect in order to reset the data and activate the behaviors.

Here is what I am doing to change the contents of the SELECT list on the left.

Do I need to do something to get the behaviors working after reloading the left side in this manner?

    $(function() {
	$(".LoadListType").click(function() {
		dataString = "";
		$.ajax({
			type: "POST",
			url: "../_data/ajax_recipient_ddl.asp", 
			data: dataString,
			success: function(data) {
				$('#leftpanel').html('<input type="text" name="q" class="form-control" placeholder="Search..." />')
				.append(data)
			}
		});
	});
    });

**Comment by rgalpin** [comment]
The code I posted is not displaying $('#rightpanel').html('') correctly. Inside the .html('') it should have the input tag for the search box. 
lessthan input type="text" name="q" class="form-control" placeholder="Search..." / greaterthan

This is my first post on here - so please forgive if there is some tool or convention for posting code.

**Comment by crlcu** [comment]
Hi @rgalpin,
I have tested the plugin with the following code:
```javascript
$('#multiselect').multiselect();

        $.ajax({
            url: 'options.json',
            dataType: 'json',
            success: function(json) {
                var options = '';

                for (index in json) {
                    options += '<option value="' + json[index]['value'] + '">' + json[index]['text'] + '</option>';
                }

                $('#multiselect').html(options);
            }
        });
```
and everything works fine.
