### ISSUE TITLE
moveToRight, there is a copyToRight and clearFromRight

### ISSUE THREAD

**Issue by 9723** [crlcu/multiselect#29]
Hi, many thinks multiselect project.
There is a function in my mini project.  Multiple right selects, just one left select. So when i clicked "copyToRight" button, the value of option from left select will  copy to one of  right selects. When i click the "clearFromRight" button, the value of option will disappear from right select.How about this feature?

**Comment by crlcu** [comment]
Just to double check the scenario,

When the page is rendered, you have a set of ``options`` in ``left`` and another set of ``options`` in ``right``.
What you want to have is kinda ``go back to initial state`` ?

**Comment by 9723** [comment]
Yes, it's kinda `go back to initial state` in the `left` select. But the `right selects` maybe have the same value of option from `left` select clicked. multiselect's actions are the same page.  so I ask the question.
And `go back to initial stat` in the `left` select is a good ideas.I will  try to code it. Thanks your reply.

**Comment by crlcu** [comment]
Ok, go on and let me know when you have something.

**Comment by crlcu** [comment]
Please reopen this thread when you have done something.
Cheers.
