### ISSUE TITLE
top button alignment

### ISSUE THREAD

**Issue by rogeroliveira84** [crlcu/multiselect#30]
There is a problem with the first button, it can be the undo or >> buttons, it shows a bit to the left not aligned with the others. I don't know if this problem is related to incompatibility with bootstrap 3 or no.

![untitled](https://cloud.githubusercontent.com/assets/10275369/12381034/c1429082-bdd5-11e5-89b6-f0d69ebbf1e8.png)

**Comment by crlcu** [comment]
Hi @rogeroliveira84 
Could you please provide some example code ?
Maybe a link to jsfiddle ?

**Comment by rogeroliveira84** [comment]
Hi @crlcu sorry, I just saw your request for a example code, this problem was a css issue in my side, no worries. all good.
