### ISSUE TITLE
Search functionality not working in any version of IE

### ISSUE THREAD

**Issue by m42martin** [crlcu/multiselect#31]
Hi.  This is a great control.  

The search functionality is not working in IE.
I checked your demo page and verified that this is not just happening on my web page.

Typing in the search field in IE doesn't result in immediate filtering.
Clicking enter while in the search field in IE 8+ doesn't have any effect.

Hopefully you'll be able to patch that.  For now, I'm going to hide the search fields in IE to avoid problems.

Thanks,

**Comment by crlcu** [comment]
Hi @m42martin,
Release v2.1.6 might fix this issue.

**Comment by m42martin** [comment]
Confirmed.  Works in IE 8+.
Thanks for your speedy response.
