### ISSUE TITLE
Items are selected when posting page

### ISSUE THREAD

**Issue by m42martin** [crlcu/multiselect#32]
When posting the page, items that are not selected in the select controls are automatically selected.

This is especially noticeable in IE either because the page posts back slightly slower, or because the selection of each item in the list takes a bit longer.  In IE, I can watch each item highlight as it the 'selected' property is added to the option item.

Is this expected / necessary behavior?  I'm wondering if it could be optional - or if we could choose to change the styling on the selected items (for post back only) so that they don't appear to be selected.

Thanks very much.

**Comment by crlcu** [comment]
Hi @m42martin,
Yes this behavior is correct, otherwise you get nothing on the server side.
I'll have a look if there's something I can do via CSS.

**Comment by m42martin** [comment]
Thanks for looking into it!
