### ISSUE TITLE
Bug detected...

### ISSUE THREAD

**Issue by FiorellaG** [crlcu/multiselect#33]
Hi,
I'd like to point you to a bug which i detected:
when you add the search option and type one character to filter ,Tab to right_all_Button and press space, the items on the left side will be disapeared and there is no chance to bring them back without reloading the page!!
Thx
RG

**Comment by crlcu** [comment]
Hi @FiorellaG],
Release [v2.1.7](https://github.com/crlcu/multiselect/releases/tag/v2.1.7) might fix this issue.

**Comment by FiorellaG** [comment]
Hi Adrian,
thx a lot for your quick reply. unfortunately the issue is still 
existing :-(
This happens in multidestinations..
//==============================================================

$('#multi_d').multiselect({
             right: '#multi_d_to, #multi_d_to_2',
             rightSelected: '#multi_d_rightSelected, 
#multi_d_rightSelected_2',
             leftSelected: '#multi_d_leftSelected, #multi_d_leftSelected_2',
             rightAll: '#multi_d_rightAll, #multi_d_rightAll_2',
             leftAll: '#multi_d_leftAll, #multi_d_leftAll_2',
search: {
             left: '<input type="text" name="q" class="form-control" 
placeholder="Search..." />'
           },
             moveToRight: function(Multiselect, options, event, silent, 
skipStack) {
                 var button = $(event.currentTarget).attr('id');

                 if (button == 'multi_d_rightSelected') {
                     var left_options = 
Multiselect.left.find('option:selected');
                     Multiselect.right.eq(0).append(left_options);

//===================================================================

Regards
Ghaboli

Am 01.02.2016 um 10:58 schrieb Adrian Crisan:

**Comment by crlcu** [comment]
Hi @FiorellaG 
The issue here is that you have to change your code to:

```javascript
...
var left_options = Multiselect.left.find('> option:selected');
Multiselect.right.eq(0).append(left_options);
...
```

**Comment by crlcu** [comment]
Hi @FiorellaG,
Release [v2.1.8](https://github.com/crlcu/multiselect/releases/tag/v2.1.8) just went out. This has now a full fix of the issue.
The issue was not just in your code - but in multiselect lib as well.

Thanks for pointing out this issue.
