### ISSUE TITLE
Size attribute of the select control doesn't change height

### ISSUE THREAD

**Issue by m42martin** [crlcu/multiselect#34]
It appears that changing the size attribute doesn't affect the height of the control.
Is this a bug or expected?

`select name="from[]" id="multiselect_search" runat="server" size="50" multiple="true"
`
As a work-around, I'm doing this with CSS.

```
select#multiselect_search {
	height: 300px;
}	
```

Thank you.

**Comment by crlcu** [comment]
That might be an issue with the css you use in your project.

**Comment by m42martin** [comment]
OK. Thank you.  I'll keep looking.  I'm only using a sub-set of the bootstrap CSS, which may have something to do with the problem.

**Comment by crlcu** [comment]
Did you managed to find out what was the issue?
