### ISSUE TITLE
Search in IE11

### ISSUE THREAD

**Issue by PawanSomani** [crlcu/multiselect#35]
Hi, 
Thanks for give good plugin. Unfortunately we are facing issue with search i.e. its not working in IE11 where as it works fine in Chrome.

Thanks

**Comment by crlcu** [comment]
Hi @PawanSomani 
Are you talking about the existing demo page?
If yes, could you try again please, I have just updated the demo page with the latest version of the plugin.

**Comment by PawanSomani** [comment]
Thanks Crisan, Now its working fine.
