### ISSUE TITLE
2 Search in same page

### ISSUE THREAD

**Issue by MarlonMiranda** [crlcu/multiselect#37]
Hello, i need to 2 Search in same page, how i can to do this ?

**Comment by crlcu** [comment]
Hi @MarlonMiranda 

Well, you can have it by simply adding something like this
```javascript
$('#with_search_1').multiselect({
...
    search: {
        left: '<input type="text" name="q" class="form-control" placeholder="Search..." />',
        right: '<input type="text" name="q" class="form-control" placeholder="Search..." />',
    },
...
});

$('#with_search_2').multiselect({
...
    search: {
        left: '<input type="text" name="q" class="form-control" placeholder="Search..." />',
        right: '<input type="text" name="q" class="form-control" placeholder="Search..." />',
    },
...
});
```

**Comment by MarlonMiranda** [comment]
Hi!
So, I need insert two "multiselect" and two panels "from - to". My problem is duplicate ids. I don't know how to alter this on script
>                                    <div class="col-sm-5">
                                        <%--<input type="text" name="q" class="form-control" placeholder="Search..."/>--%>
                                        <select name="from[]" id="search" class="form-control" size="8" multiple="multiple">
                                            <asp:Repeater ID="repeterCentrodeCustoDisponivel" runat="server">
                                                <ItemTemplate>
                                                    <option value="<%# Eval("CodigoCentroCusto") %>" data-position="<%# Eval("CodigoCentroCusto") %>" style="display: block;"><%# Eval("NomeCentroCusto") %></option>
                                                </ItemTemplate>
                                            </asp:Repeater>
                                        </select>
                                    </div>
                                    <div class="col-sm-2">
                                        <button type="button" id="search_rightAll" class="btn btn-block"><i class="glyphicon glyphicon-forward"></i></button>
                                        <button type="button" id="search_rightSelected" class="btn btn-block"><i class="glyphicon glyphicon-chevron-right"></i></button>
                                        <button type="button" id="search_leftSelected" class="btn btn-block"><i class="glyphicon glyphicon-chevron-left"></i></button>
                                        <button type="button" id="search_leftAll" class="btn btn-block"><i class="glyphicon glyphicon-backward"></i></button>
                                    </div>
                                    <div class="col-sm-5">
                                        <%--<input type="text" name="q" class="form-control" placeholder="Search..."/>--%>
                                        <select name="to[]" id="search_to" class="form-control" size="8" multiple="multiple">
                                            <asp:Repeater ID="repeterCentroDeCustoUtilizado" runat="server">
                                                <ItemTemplate>
                                                    <option value="<%# Eval("CodigoCentroCusto") %>" data-position="<%# Eval("CodigoCentroCusto") %>" style="display: block;"><%# Eval("NomeCentroCusto") %></option>
                                                </ItemTemplate>
                                            </asp:Repeater>
                                        </select>
                                    </div>

> 

And...

>                                     <div class="col-sm-5">
                                        <select name="from[]" id="search_2" class="form-control" size="8" multiple="multiple">
                                            <option value="1" data-position="1" style="display: block;">Teste</option>
                                        </select>
                                    </div>
                                    <div class="col-sm-2">
                                        <button type="button" id="search_rightAll_2" class="btn btn-block"><i class="glyphicon glyphicon-forward"></i></button>
                                        <button type="button" id="search_rightSelected_2" class="btn btn-block"><i class="glyphicon glyphicon-chevron-right"></i></button>
                                        <button type="button" id="search_leftSelected_2" class="btn btn-block"><i class="glyphicon glyphicon-chevron-left"></i></button>
                                        <button type="button" id="search_leftAll_2" class="btn btn-block"><i class="glyphicon glyphicon-backward"></i></button>
                                    </div>
                                    <div class="col-sm-5">
                                        <select name="to[]" id="search_to_2" class="form-control" size="8" multiple="multiple">
                                            <option value="1" data-position="1" style="display: block;">Teste</option>
                                        </select>
                                    </div>
                                </div>

**Comment by crlcu** [comment]
Hi,
I'm sorry, but I can't see where do you have duplicate ids.

**Comment by MarlonMiranda** [comment]
Hi,
How can I implement JS? Because my problem is duplicate multiselect. Yes, in this example don't have duplicate id's but on JS I don't know how implement a second multiselect.

Thank you!

**Comment by crlcu** [comment]
If you go to the demo page you will see there multiple multiselects on same
page.
