### ISSUE TITLE
Undo and redo

### ISSUE THREAD

**Issue by elm** [crlcu/multiselect#4]
I would like to have undo and redo for this. If I have time I might look into it but for now this is just a feature request :)

I think this could be implemented by giving each option an id and creating a list of command-objects that contain a set of ids and a direction. When undo is called it simply looks at the direction and does the opposite with all options that are listed. Then the command-object is moved to a redo list. Every time the user clicks an action the redo list is emptied.

**Comment by crlcu** [comment]
Hi @elm,

I would be nice if you can have a look and implement this feature.

**Comment by crlcu** [comment]
Hi @elm 

I've created a branch "undo_redo" and I implemented the undo / redo functionality.
I really appreciate if you can have a look and test it.

**Comment by crlcu** [comment]
[v2.0.0](https://github.com/crlcu/multiselect/tree/v2.0.0) now supports undo and redo
