### ISSUE TITLE
submitAllRight uses submitAllLeft setting

### ISSUE THREAD

**Issue by tanj** [crlcu/multiselect#40]
https://github.com/crlcu/multiselect/blob/master/js/multiselect.js#L65

Line 65 reads:
submitAllRight:     settings.submitAllRight !== undefined ? settings.submitAllLeft : true,

Should read:
submitAllRight:     settings.submitAllRight !== undefined ? settings.submitAllRight : true,

**Comment by crlcu** [comment]
Hi @tanj 
Thanks for telling me about this issue.
A fix has pushed and the issue is now fixed.
