### ISSUE TITLE
Search is case sensitive

### ISSUE THREAD

**Issue by wlrichards** [crlcu/multiselect#41]
Due to the use of the ":contains" selector the search is case sensitive. Your plugin is very useful but I do need case insensitive search. Would it be possible to provide a way to override the search?

**Comment by crlcu** [comment]
Hi @wlrichards 
A fix was made and now search is case insensitive.
Fix is added by release v2.2.3

**Comment by wlrichards** [comment]
Wow! Thanks so much for the prompt response. I will try it out tomorrow.


Sent from my Xperia™ tablet

---- Adrian Crisan wrote ----

Hi @wlrichards
A fix was made and now search is case insensitive.
Fix is added by release v2.2.3

---
