### ISSUE TITLE
Safari Support for "Move All"

### ISSUE THREAD

**Issue by diego-qgenda** [crlcu/multiselect#44]
1. Open your demo (http://crlcu.github.io/multiselect/) in Safari (v8.0 or v9.0, maybe others)
2. None of the "Move All" (>> or <<) in the demo work

**Comment by diego-qgenda** [comment]
BTW: your change on issue #45 will also fix this one :)

```
var $options = self.$left.children(); //instead of self.$left.children()(':visible');
...
var $options = self.$right.children(); //instead of self.$right.children()(':visible');
```

**Comment by crlcu** [comment]
Hi @diego-qgenda 

The last release (2.2.5) just went out and this issue is now fixed.
