### ISSUE TITLE
IE support for "Move All"

### ISSUE THREAD

**Issue by diego-qgenda** [crlcu/multiselect#45]
1. Open your demo (http://crlcu.github.io/multiselect/) in IE11 (maybe others)
2. None of the "Move All" (>> or <<) in the demo work

**Comment by Majoros** [comment]
I am seeing the same issue. The IE 11 debugger shows no errors being thrown.

**Comment by Majoros** [comment]
I removed ':visible' from the rightAll.on and leftAll.on functions 

`                self.actions.$rightAll.on('click', function(e) {
                    e.preventDefault();

                    //var $options = self.$left.children(':visible');
                    var $options = self.$left.children();

                    if ( $options.length ) {
                        self.moveToRight($options, e);
                    }

                    $(this).blur();
                });
`

I have no idea why this fixes the problem or that its the correct solution.

**Comment by diego-qgenda** [comment]
Cool, that fixes it. Are you going to commit these changes and create a new version?

**Comment by diego-qgenda** [comment]
Also you should updated your demo (http://crlcu.github.io/multiselect/) with this changes :)

**Comment by crlcu** [comment]
Hi @diego-qgenda 

The last release (2.2.5) just went out and this issue is now fixed.
