### ISSUE TITLE
possible fixes

### ISSUE THREAD

**Issue by illuminate3** [crlcu/multiselect#5]
Thank you for your multiselect code!

Still testing this but these are a few things that caught my eye:
1. upgrade to newer boostrap
2. I'm not a jquery guy but the focus stays on the middle buttons when clicked
3. possibly a way to automate the size='8' attribute

This is what I'm using for html

```
<div class="row">
	<div class="col-sm-5">
		<select name="from" id="multiselect" class="col-sm-12" size="12" multiple="multiple">
			<option value="1">Item 1</option>
			<option value="2">Item 5</option>
			<option value="2">Item 2</option>
			<option value="2">Item 4</option>
			<option value="3">Item 3</option>
		</select>
	</div>

	<div class="col-sm-2">
		<button type="button" id="multiselect_rightAll" class="btn btn-default btn-block"><i class="fa fa-fast-forward fa-fw"></i></button>
		<button type="button" id="multiselect_rightSelected" class="btn btn-default btn-block"><i class="fa fa-chevron-right fa-fw"></i></button>
		<button type="button" id="multiselect_leftSelected" class="btn btn-default btn-block"><i class="fa fa-chevron-left fa-fw"></i></button>
		<button type="button" id="multiselect_leftAll" class="btn btn-default btn-block"><i class="fa fa-fast-backward fa-fw"></i></button>
	</div>

	<div class="col-sm-5">
		<select name="to" id="multiselect_to" class="col-sm-12" size="12" multiple="multiple"></select>
	</div>
</div>
```

**Comment by crlcu** [comment]
Hi @illuminate3 

1. I would really appreciate if you can do a "bootstrap3.html" version which will use the latest bootstrap and create a pull request.
2. I made a change to remove focus from clicked button.
3. Regarding size="8", I'm not sure if it needs changing, because it's up to the dev that is using this plugin to choose which will be the size for his "select" elements.

**Comment by crlcu** [comment]
[v2.0.0](https://github.com/crlcu/multiselect/tree/v2.0.0) has now a [demo page](http://crlcu.github.io/multiselect/) with [Bootstrap 3](http://getbootstrap.com/)
