### ISSUE TITLE
startup remove doesn't seem to work

### ISSUE THREAD

**Issue by msRay** [crlcu/multiselect#52]
I'm sorry in advance if I am posting this in the wrong location but I couldn't figure out what to do.  I like the plugin for Jquery but I'm having an issue.  I'm using it in my java application and I managed to pass the full list of items to my jsp page and the selected list via a form to the jsp.  The page renders will the fill list on the left with all the items selected that I want.  But what I can't figure out how to do is to get the selected items rendered in the right.  The way I read the documentation I thought startUp would default to remove which would remove the selected items from the left and put them in the right.  My right select list has nothing in it.  I appreciate any help on this.  

[jspCode.txt](https://github.com/crlcu/multiselect/files/215953/jspCode.txt)

**Comment by crlcu** [comment]
Could you please update to the latest version and try again?
