### ISSUE TITLE
Ajax post doesnt receive selected values

### ISSUE THREAD

**Issue by gntvls** [crlcu/multiselect#54]
Hello, not sure what is happening, but when i post some selected values via ajax, i cannot get them,
http://i.imgur.com/8VkDnII.png . I'm also using 3rd party ajax fraamework called Sijax, i tought it is this plugin issue, but then i tried with standard ajax, it is the same.

This is my init script:

`$('#search').multiselect({
            submitAllLeft: false,
            submitAllRight: true,
            search: {
                left: '<input type="text" name="q" class="form-control" placeholder="Search..." />',
                right: '<input type="text" name="q" class="form-control" placeholder="Search..." />',
            }
        });`

This is ajax submit function:
`$.ajax({
            type: "POST",
            url: "/tools/testpost.php",
            data: $("#domainsgroup").serialize(), // serializes the form's elements.
            success: function (data)
            {
                alert(data); // show response from the php script.
            }
        });`

And the output is in the screenshot. One time it was ok, when i did search, the selected all, and by doing this it worked fine, but if select one by one without searching, then something is not right. I was trying to do this on click submit, before requesting via ajax:

`$("select#search_to option").each(function () {
         $(this).attr("selected", "");
         //console.log($(this));
         });`

Not sure if i'm doing something wrong or what is happening. Also i tried simple form post, then it worked ok, but with ajax i have problems. Thanks!

**Comment by gntvls** [comment]
Looks like this code fixed the issue:

`$("select#search_to option").each(function () {
            $(this).prop("selected", true);
        });
            var values = Sijax.getFormValues("#domainsgroup");
            Sijax.request("submitDomainsGroupList", [values]);`

**Comment by crlcu** [comment]
Hi @gntvls,
When sending the values via ajax, you have to manually set the property ``selected`` to true, as you already found out.

**Comment by gntvls** [comment]
Yeah, thanks! Nice plugin!

**Comment by crlcu** [comment]
No worries.
Thanks.
