### ISSUE TITLE
Delay in posting form with 2.2.6

### ISSUE THREAD

**Issue by sparkyuk2104** [crlcu/multiselect#56]
I love this plugin, but have a small question or two:

With 2.2.6 I'm seeing a delay from when I click my form's submit button, that I believe I didn't see with releases prior to 2.2.6.

In addition, the left (from[]) side now removes the select element prior to posting, which never appeared to happen with older versions.

Is there some clean-up going on before control is passed to the form handler? This delay can be around 500ms-1000ms. I cannot seem to prevent this. The select element (from[]) contains around 200 items.

Thanks in advance.

**Comment by crlcu** [comment]
Could you please check if this is still happening with the latest version and reopen the issue if so ?

Thanks.
