### ISSUE TITLE
Using optgroups breaks keepRenderingSort

### ISSUE THREAD

**Issue by MazeChaZer** [crlcu/multiselect#58]
When `keepRenderingSort` is set to `true`, the options fall out of their optgroups after being moved. Also empty optgoups are still being displayed. Example: http://jsbin.com/tozexepoci/edit?html,js,output

**Comment by crlcu** [comment]
Hi @MazeChaZer 
A release was made in order to fix this issue.

**Comment by MazeChaZer** [comment]
Thanks!

**Comment by MazeChaZer** [comment]
Thanks!

**Comment by MazeChaZer** [comment]
Thanks!

**Comment by MazeChaZer** [comment]
Thanks!

**Comment by MazeChaZer** [comment]
Thanks!

**Comment by MazeChaZer** [comment]
Thanks!
