### ISSUE TITLE
double-click not working in new IE (11 and 12)

### ISSUE THREAD

**Issue by chaau** [crlcu/multiselect#6]
There is a hack in the code to support the double-click:

```javascript
				// dblclick support for IE
				if ( navigator.userAgent.match(/MSIE/i) ) {
					self.left.dblclick(function(e){
						actions.rightSelected.trigger('click');
					});
					
					self.right.dblclick(function(e){
						actions.leftSelected.trigger('click');
					});
				}
```
The useragent string got changed in the newer versions of IE. The code needs to be enhanced. Check this out: http://stackoverflow.com/questions/19999388/jquery-check-if-user-is-using-ie

The proposed enhancement is:

```javascript
				// dblclick support for IE
				if ( navigator.userAgent.match(/MSIE/i)  || navigator.userAgent.indexOf('Trident/') > 0 || navigator.userAgent.indexOf('Edge/') > 0) {
```

**Comment by crlcu** [comment]
Hi @chaau 
The bug should be fixed now.

Thanks for letting me know about this issue.
