### ISSUE TITLE
Multiple destinations Doesn't Works Safari

### ISSUE THREAD

**Issue by eliasleyton** [crlcu/multiselect#61]
Hi,

Multiple destinations doesn't Work, button all right, or button all left, nothing do. 

You can helpme?

**Comment by NewtCobell** [comment]
I've run into the same problem - the single left and single right buttons work just fine, but the move all left and right buttons don't do anything on multiple destination.  Only having this issue in Safari so far - it's working fine in Chrome, IE, and Firefox.  Thanks!

**Comment by billyeh** [comment]
FWIW I've just tested this on Safari and it works now at least. Perhaps fixed by a Safari update.
