### ISSUE TITLE
Using with asp.net webforms

### ISSUE THREAD

**Issue by ventil8** [crlcu/multiselect#65]
Everything is setup and working...I am pulling the content from the DB and it displays and moves well. Whenever I submit my page I can grab any of the values, I use a very simple.

` For Each aItem As ListItem In Me.ddlgroups_to.Items
                _employee.Groups.Add(Int32.Parse(aItem.Value))
            Next`

Where the ddlgroups_to is my destination select. Is this a limitation of the plugin or .net itself?

**Comment by crlcu** [comment]
Hi,
Nope, the plugin doesn't have any limitations.

**Comment by ventil8** [comment]
Strange cannot get any value from the second multiselect...

**Comment by crlcu** [comment]
Could you provide some code example ?

**Comment by ventil8** [comment]
its the fact that I am using .net. The target list does not have anything according to .net, need to use a hidden field. So i guess this is not issue at all with the plugin.

**Comment by ventil8** [comment]
I just need the ddlgroups_to dropdownlist to always be selected after we move items accross...that way asp.net can get the values...is this possible to change?

**Comment by crlcu** [comment]
Hi @ventil8 
If the `select` elements are in a `form` then, when the form is submitted, all the values are selected, from both sides (left and right).

**Comment by ventil8** [comment]
my select elements were in a form but the values were not being selected from any side (I could get this to work by manually selecting the items on the RHS then clicking out of the select, not ideal.. ;-)). I have added some JS code to make this happen on my page when a user clicks the submit button and it works really well now. I think it would be really cool if you could decide which side you wanted to submit? Great plugin though...

**Comment by crlcu** [comment]
How is that form submitted ?
Via `ajax` - if is sent via `ajax` you have to handle the `select all options`.

As I said, the plugin is handling the form submit:

```javascript
...
// Select all the options from left and right side when submiting the parent form
self.$right.closest('form').on('submit', function(e) {
    self.$left.find('option').prop('selected', self.options.submitAllLeft);
    self.$right.find('option').prop('selected', self.options.submitAllRight);
});
...
```

**Comment by ventil8** [comment]
No Ajax...just standard asp.net webforms. I will have a look at things again today to see if I have missed anthing...I ended up adding something similar to the following for my save button.

`self.$right.find('option').prop('selected', self.options.submitAllRight);`
