### ISSUE TITLE
Sort breaks optgroup

### ISSUE THREAD

**Issue by Saruspete** [crlcu/multiselect#67]
Hello,

First, thanks for this tools, it saved me a lot of time.

I've used the example of optgroup & search on the website, and ran into an issue when using it.

```
$("#fields").multiselect({
  search: {
    left: '<input type="text" name="q" class="form-control" placeholder="Search..." />',
  },
});
```

 After debugging, the logic of moveToLeft / moveToRight are good, the issue comes just after, when trying to sort the list :

```
if ( typeof self.callbacks.sort == 'function' && !silent ) {
  self.$right.mSort(self.callbacks.sort);
}
```

Seems the default of sorting the values is breaking the hierarchy between the groups, placing every object at the same level.

I solved it by adding "sort: false" to the construction, but it should be managed by default.

thanks for this lib again ! :)

**Comment by joshkg** [comment]
At the moment, [sort & search are disabled if optgroups are present](https://github.com/crlcu/multiselect/blob/master/js/multiselect.js#L83).

**Comment by Saruspete** [comment]
Sorry for the lack of followup, I was on vacations. 

I saw the comment, but the check is only done at startup. In my case, I'm populating content from Ajax at load time, and the initial list is empty, so search & group are not disabled.

While I saw why sort breaks stuff, why disabling searching ? it's working perfectly.
Also, I've tried to hide optgroups which were empty during search, so not to clutter the list of remaining objects. 
Just add `self.$left.find('option:hidden').parent().not( $(":visible").parent() ).hide();`
right after `var $toHide = self.$left.find('option:not(:search("' + this.value + '"))').mHide();`

and same for $right.

Sorry not to propose a PR, i'm a bit lacking some correct git env for the time being...

**Comment by crlcu** [comment]
Hi @Saruspete 
It would be really helpful if you could do the changes and open a pull request.

**Comment by Saruspete** [comment]
Created. However, I don't know how I can handle the sort issue at load time.
Maybe with events, but I didn't do js since a long time...

**Comment by crlcu** [comment]
Starting with v2.3.7 keep rendering sort is supported even if there are optgroup's
