### ISSUE TITLE
afterMoveToRight issue

### ISSUE THREAD

**Issue by patrick-yv** [crlcu/multiselect#68]
Hello,
It seems that there is a problem with afterMoveToRight function.
When I add items to the right side there is no problem I can get there values with $options parameter of the afterMoveToRight function .
But If I add a new item to right side, I do not get the total of items in $options object but only the last one. I am waiting for retrieving the whole set of right items.
Could you have a look to this issue ?
Thank you 
Good job.
Patrick

**Comment by crlcu** [comment]
Hi @patrick-yv 

I'm not sure I understand the issue, could you please be a bit more specific, like describing all the steps you make ?

**Comment by patrick-yv** [comment]
Hi,
Here is my code for afterMoveToRight :
afterMoveToRight: function($left, $right, $options) {
                var deptIds = [];   
                $options.each(function(i, val){
                    deptIds[i] = $(val).val();
                });
                getOptions("DEPARTMENT", deptIds);  
},.....
Here is the issue : $options array doesn't contain all the move to right Items if a user add item one by one.
Thank you for this nice plugin.

**Comment by crlcu** [comment]
Hi @patrick-yv 

If you have a look at the [documentation](http://crlcu.github.io/multiselect/#afterMoveToRight) - you'll see that `$options` is a `jQuery element containing all selected options`.

Hope that helps.

**Comment by patrick-yv** [comment]
Thank you for your answer,
Ok I just understand that $options contains the selection made on left side by the user. 
How could I get the options list on the right side after move to right without using DOM ?

**Comment by crlcu** [comment]
Try:

```javascript
$right.children();
```
