### ISSUE TITLE
1 click MoveToRight or MoveToLeft

### ISSUE THREAD

**Issue by douglasdeodato** [crlcu/multiselect#69]
Hi,

thanks for the plugin its really amazing.

right now I need click 2 times in the element to move to right or left, how can I move this element with just one click instead of 2?

thank you.

**Comment by crlcu** [comment]
Hi @douglasdeodato 

The easiest way is something like this

```javascript
$('option').on('click', function() {
    $(this).trigger('dblclick');
});
```

**Comment by douglasdeodato** [comment]
@crlcu  thank you.

**Comment by addaddc** [comment]
How to cancel the subscription?

Regards,
Eric Chen

**Comment by douglasdeodato** [comment]
@addaddc  stop watch the project, right top corner
