### ISSUE TITLE
Origin data in right select is not in request parameter

### ISSUE THREAD

**Issue by tzwm** [crlcu/multiselect#7]
Hi, I like to use your multiselect plugin. But I have a problem.

I put some origin data in right select when server render the page:

``` html
<select multiple="multiple" id="multiselect_to" name="ids">
  <option value="1">test1</option>
  <option value="2">test2</option>
</select>
```

When I post the form include above selects to server, I found the origin data is not in the parameter of request. But the data I selected by clicking the "moveToRight" button is in request parameters.

I'm confused about this. Could you help me? Thanks.

**Comment by crlcu** [comment]
You mean you have let's say 2 options in the right side by default when the page is rendered, after that you move some other options to the right side but only those that was moved after page render are sent back to server ?

**Comment by tzwm** [comment]
@crlcu Yes. That's my problem.

**Comment by crlcu** [comment]
Ok,
I'll have a look and I'll add a fix for this issue.

Thanks for reporting the issue.

**Comment by crlcu** [comment]
Hi @tzwm 
The issue should be fixed now.

**Comment by tzwm** [comment]
@crlcu Thanks!
