### ISSUE TITLE
Always add to the end of the list

### ISSUE THREAD

**Issue by 00cpxxx** [crlcu/multiselect#77]
I checked all examples but could not find a way to keep the list elements in the order I added, they always auto sort. At first I thought keep rendering sort was supposed to do this but it is not for that as the examples prove.

Is there any way to achieve what I need?

Thanks for the great library.

**Comment by crlcu** [comment]
Hi @00cpxxx,

Have you tried with `sort: false` ?

**Comment by 00cpxxx** [comment]
Yes, I missed that in the docs, sorry. The expected result was almost perfect, The right list works like a charm, but when I put the items back in the left list they will also be affected by the sort: false (naturally). I made a hack to the code in order to support sort: 'target' to only sort the right list. I don't expected this non-standard behavior to be accepted so I'm closing the issue.
