### ISSUE TITLE
Not working properly on ipad

### ISSUE THREAD

**Issue by nationdata-it** [crlcu/multiselect#78]
Not working properly on ipad

**Comment by crlcu** [comment]
Hi @nationdata-it 

If you have a look at http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_multiple from your ipad, you will see that there's a bug on IOS.

Anyway, I will try to find a solution to this problem (if there is one).

**Comment by nationdata-it** [comment]
Yes i know that that issue is on ios, but i was wondering if you have any solution to that.
you can have some thing like http://loudev.com/

**Comment by crlcu** [comment]
I know that plugin,
But that's something else, that's converting `select` elements into `ul` elements.

**Comment by nationdata-it** [comment]
yes exactly, mean while i will be also looking for the solution.
if i found any thing i will let you know. except this plugin is really working good, like callback functions.

**Comment by crlcu** [comment]
@esetnik the w3schools example is still not working for me on ios
![image](https://user-images.githubusercontent.com/1661844/48001152-62e98e80-e110-11e8-8133-ac17eca761e6.png)

**Comment by esetnik** [comment]
What about it isn’t working?
