### ISSUE TITLE
Two Destinations

### ISSUE THREAD

**Issue by stb74** [crlcu/multiselect#8]
Hi

Is it possible to have multiple destinations.  I will have a main list of players that I want add to list 1 for starting 11 and add to list 2 with what is left for substitutions list.

Many Thanks
Scott

**Comment by crlcu** [comment]
Hi @stb74 

I'll have a look and I'll let you know once I have a resolution.

**Comment by stb74** [comment]
Many thanks.

Scott

**Comment by crlcu** [comment]
Hi @stb74 

Just to make sure I understand what you need:
You will have a LEFT select and from that LEFT you want to put options in multiple RIGHT selects ?

**Comment by stb74** [comment]
Yes.  I will have a list of players (select1) and will move them to
starting 11 (select2) or Substitutes (select3)

If it too much trouble don't worry about it.

**Comment by crlcu** [comment]
Hi @stb74 

I've updated the demo page with an example for two destinations in right side.
Url: http://crlcu.github.io/multiselect/#demo-multiple-destinations

Please let me know if this looks ok for your needs.

**Comment by stb74** [comment]
I have tested it and at the moment it doesn't work as expected  for me.
Using your code example is fine but I dynamically load the data from  a
database and second right select is showing me what's on the first select.

When I get some time I will try and investigate.

Thanks
Scott

**Comment by crlcu** [comment]
Could you put some code sample here ?
Or send via email ?

**Comment by stb74** [comment]
Was there much changes to the multiselect.js as they appear the same.

**Comment by crlcu** [comment]
Yes, there are changes to multiselect.js as well, not only to the demo file.

**Comment by stb74** [comment]
I noticed that I had downloaded the same version as before so downloaded
v2.1.0 but the same issue and js appears the be same.

**Comment by stb74** [comment]
And might just be a typo but both state they are version 2.0.0

**Comment by crlcu** [comment]
It can't be the same.
Have a look at multiselect.js and check if this line is there

``` javascript
return self.callbacks.moveToRight( self, options, event, silent, skipStack );

**Comment by crlcu** [comment]
Yep, it was just type :D.
Fixed now

**Comment by stb74** [comment]
Not sure how I get the data for you to test this, I have pasted my html etc
below for you to see.  It appears to be duplicating multi_d_to into
multi_d_to_2 .

http://www.codeshare.io/86QSa

**Comment by stb74** [comment]
I think the problem is

right: '#multi_d_to, #multi_d_to_2',

If I take #multi_d_to_2 out it displayed the correct data.

**Comment by crlcu** [comment]
I've got the bug.
I'll have a look and prepare a fix.

**Comment by crlcu** [comment]
Quick fix until I'll push a new commit:

add: ``keepRenderingSort: true,``

``` javascript
$('#multi_d').multiselect({
			right: '#multi_d_to, #multi_d_to_2',
			rightSelected: '#multi_d_rightSelected, #multi_d_rightSelected_2',
			leftSelected: '#multi_d_leftSelected, #multi_d_leftSelected_2',
			rightAll: '#multi_d_rightAll, #multi_d_rightAll_2',
			leftAll: '#multi_d_leftAll, #multi_d_leftAll_2',
			keepRenderingSort: true,
...

**Comment by crlcu** [comment]
Hi @stb74 

Latest commit should fix this bug now.

**Comment by stb74** [comment]
That fix works but I need the first of the right selects to retain its
original sort.  I have also disabled the sort from your code

The main list is a list of players,  second is starting 11 and third is
Substitutes. The starting 11 will be stored in database on submitted order.

Thanks
Scott

**Comment by crlcu** [comment]
To keep what ever sort you want you can specify a custom ``sort`` function.
