### ISSUE TITLE
left side is optgroup, right side is not optgroup?

### ISSUE THREAD

**Issue by liuyug** [crlcu/multiselect#80]
Hi,

Thanks for your multiselect.

I have a issue about optgroup.

My left side is optgroup, right side is not optgroup

How to ignore optgroup when move to right.

**Comment by crlcu** [comment]
Basically you would like to have `options` grouped by `optgroup` in left side, but once they are move to the right side, you don't need them to be grouped anymore ?

**Comment by liuyug** [comment]
Yes, I don't need optgroup in right side.

**Comment by crlcu** [comment]
In this case you have to pass a custom `moveToRight` / `moveToLeft` callbacks.
See http://crlcu.github.io/multiselect/examples/multiple-destinations.html
