### ISSUE TITLE
afterSort event

### ISSUE THREAD

**Issue by JimmyBoh** [crlcu/multiselect#82]
I'd like to know when items are moved up and down in the sort order. I know I can override the sort function, but is there a way to tap into an `afterSort` event without rewriting the default sort function?

Example:
```js
this.$el.find('select.source').multiselect({
  afterMoveToRight: changeHandler, // works
  afterMoveToLeft: changeHandler,   // works

  afterSort: function (options) { // Something like this??
    changeHandler(null, null, options);
  }
});

function changeHandler($left, $right, selected) {
  var selectedValues = selected.map(function (i, x) { return x.value; }).get();
  console.log(selectedValues);
}

**Comment by crlcu** [comment]
Hi,

That's not possible yet, but I'll have a look when I have some time.

**Comment by JimmyBoh** [comment]
Okay, thanks.

I did find somewhat of a workaround, but it is quite a hack. I just bind to the click event of the sort buttons and then grab the `options` within the `to[]` select manually. It will do for now until a correct feature exists!

(I'd normally create a PR with the change implemented, but at the moment there is no time for me to work on that. If things lighten up here I will let you know and give it a shot.)

**Comment by crlcu** [comment]
Could you please explain a bit why you would need an event like that ?

Would it be possible to obtain what you are after with other callback like `afterMoveToRight` for example ?

If you have a look at the source code, there's :
```javascript
if ( typeof self.callbacks.sort == 'function' && !silent && !self.doNotSortRight ) {
    self.$right.mSort(self.callbacks.sort);
}

if ( typeof self.callbacks.afterMoveToRight == 'function' && !silent ) {
    self.callbacks.afterMoveToRight( self.$left, self.$right, $options );
}
