### ISSUE TITLE
Feature Request: "Select All" using CTRL+A while list in focus

### ISSUE THREAD

**Issue by danowar2k** [crlcu/multiselect#83]
It would be nice if one were able to select all currently visible elements in the select elements using CTRL+A.

I know, you can filter the elements using the search box and then click on "Add All". But sometimes it would be useful to be able to select all elements and then deselect one or two of the items manually.

**Comment by crlcu** [comment]
Hi @danowar2k 

Seems like this is already possible. Have you tried and didn't worked?

**Comment by danowar2k** [comment]
Let's see...I go to the zero configuration demo [here](http://crlcu.github.io/multiselect/examples/zero-configuration.html). I click on one item in the left select box. The item is selected. On my keyboard with the German layout I press STRG+A (i.e. CTRL+A).

My setup: Firefox 50.1.0 on Windows 7 Professional 64 Bit

This should happen: All items in the left select box are selected.
This happens: The whole page text is selected, but the items aren't.

I don't understand...

**Comment by crlcu** [comment]
I have tried this on Chrome and Safari and works.

**Comment by danowar2k** [comment]
Yup, tried it in Chrome here and it works there. Hmmm, so this is probably a browser thing... Now how would I google search for CTRL+A isssues in Firefox...hmm

**Comment by danowar2k** [comment]
So if it's a Firefox problem and no workaround is possible, I'll close this here...

**Comment by NashBridgesAT** [comment]
i had the same problem but you can override it using jquery (found that partially in stackoverflow):
```

$("#js_multiselect_to_1" ).keydown(function (e) {
			if (e.ctrlKey) {
				if (e.keyCode == 65 || e.keyCode == 97) { // 'A' or 'a'
					$('#js_multiselect_to_1 option').prop('selected', true);
					e.preventDefault(); 
					return false;
				}
			}
		});
```

You are appending a keydown function when focusing the select box. This function checks if ctrl is pressed and then if A or a is pressed. With `$('#js_multiselect_to_1 option').prop('selected', true);` all options are selected.
