### ISSUE TITLE
Feature Request: Option to set minimum length for search filter activation

### ISSUE THREAD

**Issue by danowar2k** [crlcu/multiselect#85]
Hi,

right now the entries in the list are filtered when the first letter has been typed.
I don't know how the performance is when the list has thousands of entries in it, but in any case I think it would be a nice to feature to allow the user to set a minimum length to activate filtering options.

**Comment by crlcu** [comment]
This is now done. see v2.3.3

**Comment by danowar2k** [comment]
Amazing! Thank you 👍
