### ISSUE TITLE
Add multiselect to npm

### ISSUE THREAD

**Issue by neutrino84** [crlcu/multiselect#86]
Any reason why this is not on npm yet? It would be great, and I'd be very thankful, so far I've been able to successfully use it with no issue like this:

```
"dependencies": {
    "pm2": "2.0.x",
    ...
    "express": "4.14.x",
    "multiselect": "git+https://github.com/crlcu/multiselect.git"
  },
```

But this increases the time it takes to run npm install and npm update.

**Comment by crlcu** [comment]
Hi,
I have published this as https://www.npmjs.com/package/multiselect-two-sides

**Comment by neutrino84** [comment]
there is a problem in you package.json, you need to change the "index" to dist/multiselect.js

**Comment by crlcu** [comment]
Should be fixed now
