### ISSUE TITLE
Feature Request: Keep same size for select box after filtering

### ISSUE THREAD

**Issue by danowar2k** [crlcu/multiselect#88]
Example: Select box with a certain size (e.g. 8). Elements are inside the box.

CURRENT: Now when you use the search filter and nothing matches, the select box is reduced to nearly nothing, because no element remains in the box.

REQUEST/SHOULD: Select box should remain the same size and be empty (or maybe a message saying "No matching elements" or something like it).

**Comment by danowar2k** [comment]
If you use Bootstrap this problem is non existent. But I still think an element should take care of that by itself...

**Comment by danowar2k** [comment]
In this example here: http://crlcu.github.io/multiselect/examples/optgroup.html

When you move every option on the right to the left, the right box will get juuust a little bit smaller which produces a slightly irritating effect.

**Comment by danowar2k** [comment]
In this example: http://crlcu.github.io/multiselect/examples/search.html
When I filter the left side to only include Item 2 and move it to the right, the select box is reduced to 10 pixels height or so. Better would be if the select box wouldn't change its height (maybe indicate no results using a text overlayed over the select box?)

**Comment by crlcu** [comment]
This plugin does not provide `css` stuff, it's main concern is about handling the business logic.
You can customize the appearance with any `framework` or custom `css`.
