### ISSUE TITLE
Left side reorders when it changes.

### ISSUE THREAD

**Issue by tapia** [crlcu/multiselect#90]
Check this example:

http://crlcu.github.io/multiselect/examples/optgroup.html

If you move Volvo from right side to left side, then all the "Swedish cars" optgroup moves from the top of the list to the bottom. This is useless to us, because the <select> order should be fixed, and I think it would be the expected behaviour to anyone.

Moving the items from one side to another should change its visibility, not it position.

**Comment by crlcu** [comment]
This is fixed now.
