### ISSUE TITLE
Is it possible to move an option by index from right to left?

### ISSUE THREAD

**Issue by fschaeffer** [crlcu/multiselect#92]
I need to create some buttons which will move a subset of all available options from right to left. Is there a way to trigger a "move" for a single option or an array of options?

**Comment by crlcu** [comment]
Did you tried something like this ?

```javascript
$('#custom_right').on('click', function(e) {
    e.preventDefault();

    // do some additional stuff

    $('#multiselect_rightSelected').trigger('click');
});
```

**Comment by fschaeffer** [comment]
Sounds good, will give it a try. Is there also an option to (multi)select options by index value (so I can use translations for the option labels)? The complete usecase would be having a couple of options available to be moved, a button to click on which then will select some of the available options by index and move them to the selected options box.

**Comment by crlcu** [comment]
There's nothing provided by the plugin, but I thing you can do whatever you need to with `jQuery` selectors.

**Comment by fschaeffer** [comment]
Hello,

thanks to your suggestion I finally ended up with selecting fields by index value and firing a dblclick (as click on the container did nothing, nor did triggering anything).

`
$('#export_excel_presetSales').on('click', function () {
  var aSalesPresetFields = ["itemnumber", "displayText", "brand","subbrand", "salesPrice","supplierPrice", "salesstate"],
        eAvailableFields = $('#export_excel_availableFields');
  $.each(aSalesPresetFields, function (index, value) {
    eAvailableFields.val(value);
    eAvailableFields.find('option:selected').dblclick();
  });
});`
