### ISSUE TITLE
FR - Enable/Disable buttons based on selection

### ISSUE THREAD

**Issue by karldmoore** [crlcu/multiselect#94]
This is a feature request rather than a bug.  It would make sense if the buttons were enabled or disabled based on current selection.  Add/Remove when nothing is selected doesn't make sense.  Add All/Remove All only makes sense when there is something to do.

**Comment by crlcu** [comment]
I have evaluated this FR and I don't think it brings to much value to the plugin.
Anyway, this can be handled very easily from outside the plugin.
