### ISSUE TITLE
Demo with optgroups is broken

### ISSUE THREAD

**Issue by stefangabos** [crlcu/multiselect#95]
In the demo with the [optgroups](http://crlcu.github.io/multiselect/examples/optgroup.html), if after the page is loaded you click on the _>>_ button (to move all item from left to the right), the data gets lost

**Comment by crlcu** [comment]
Hi @stefangabos 
This should be fixed now.

Thanks for raising the issue.

**Comment by stefangabos** [comment]
Thanks!
