### ISSUE TITLE
keepRenderingSort: true does not maintain optgroups order

### ISSUE THREAD

**Issue by stefangabos** [crlcu/multiselect#96]
You can check with the "optgroups" example - move all Swedish cars to the right (so that the optgroup is removed from the left panel) and then move them back (either one by one or all at once). Notice that the "Swedish cars" optgroup it put at the end of the list instead of being the first.

Thanks!

**Comment by stefangabos** [comment]
Actually, rendering sort seems to be not kept at all when having optgroups

**Comment by crlcu** [comment]
This is not supported yet.
I'll have a look and I'll try to provide support for that as well.

**Comment by stefangabos** [comment]
Thanks! If you don't have time I'll try and do it myself and submit a pull request

**Comment by crlcu** [comment]
This should be done now, checkout https://github.com/crlcu/multiselect/releases/tag/v2.3.7

**Comment by stefangabos** [comment]
Seems to be working. Thanks a lot!
